# Site preparation: clear the plot, lawn, foundation podium
# generated by tools/build_functions.py -- do not edit by hand


# wipe everything that was standing on the plot
fill ~-15 ~ ~-31 ~15 ~18 ~-1 minecraft:air

# solid ground under the whole plot
fill ~-15 ~-7 ~-31 ~15 ~-2 ~-1 minecraft:stone
fill ~-15 ~-1 ~-31 ~15 ~-1 ~-1 minecraft:grass_block

# raised podium the mansion sits on (front porch included)
fill ~-12 ~ ~-27 ~6 ~ ~-8 minecraft:smooth_quartz
fill ~-12 ~-1 ~-27 ~6 ~-1 ~-8 minecraft:polished_blackstone

# polished floor inside the ground floor
fill ~-10 ~ ~-25 ~4 ~ ~-11 minecraft:quartz_block

# entrance steps up to the porch
fill ~-4 ~ ~-7 ~-2 ~ ~-7 minecraft:quartz_stairs ["weirdo_direction":2,"upside_down_bit":false]
