# Ground floor: kitchen, dining, lounge, hall, guest bath
# generated by tools/build_functions.py -- do not edit by hand


# interior partitions (open plan, so only where it matters)
fill ~-6 ~1 ~-25 ~-6 ~4 ~-19 minecraft:quartz_block
fill ~-1 ~1 ~-25 ~-1 ~4 ~-19 minecraft:quartz_block
fill ~-1 ~1 ~-22 ~-1 ~2 ~-21 minecraft:air
setblock ~-6 ~1 ~-23 minecraft:dark_oak_door ["direction":0,"door_hinge_bit":false,"open_bit":false,"upper_block_bit":false]
setblock ~-6 ~2 ~-23 minecraft:dark_oak_door ["direction":0,"door_hinge_bit":false,"open_bit":false,"upper_block_bit":true]
setblock ~-6 ~1 ~-20 minecraft:dark_oak_door ["direction":0,"door_hinge_bit":false,"open_bit":false,"upper_block_bit":false]
setblock ~-6 ~2 ~-20 minecraft:dark_oak_door ["direction":0,"door_hinge_bit":false,"open_bit":false,"upper_block_bit":true]

# guest bath / utility divider
fill ~-10 ~1 ~-21 ~-7 ~4 ~-21 minecraft:quartz_block
setblock ~-9 ~1 ~-21 minecraft:dark_oak_door ["direction":1,"door_hinge_bit":false,"open_bit":false,"upper_block_bit":false]
setblock ~-9 ~2 ~-21 minecraft:dark_oak_door ["direction":1,"door_hinge_bit":false,"open_bit":false,"upper_block_bit":true]

# kitchen / dining divider
fill ~ ~1 ~-18 ~4 ~4 ~-18 minecraft:quartz_block
fill ~1 ~1 ~-18 ~2 ~2 ~-18 minecraft:air

# - kitchen (north east)
fill ~ ~1 ~-25 ~4 ~1 ~-25 minecraft:smooth_quartz
setblock ~1 ~1 ~-25 minecraft:blast_furnace
setblock ~2 ~1 ~-25 minecraft:smoker
setblock ~3 ~1 ~-25 minecraft:cauldron
fill ~4 ~1 ~-24 ~4 ~1 ~-22 minecraft:smooth_quartz
setblock ~4 ~1 ~-23 minecraft:crafting_table
setblock ~4 ~1 ~-20 minecraft:barrel
setblock ~ ~1 ~-24 minecraft:chest
setblock ~ ~1 ~-23 minecraft:chest

# kitchen island with bar stools
fill ~1 ~1 ~-21 ~3 ~1 ~-21 minecraft:quartz_block
fill ~1 ~2 ~-21 ~3 ~2 ~-21 minecraft:quartz_slab
setblock ~1 ~1 ~-19 minecraft:dark_oak_stairs ["weirdo_direction":3,"upside_down_bit":false]
setblock ~3 ~1 ~-19 minecraft:dark_oak_stairs ["weirdo_direction":3,"upside_down_bit":false]

# - dining room (south east)
fill ~1 ~1 ~-15 ~3 ~1 ~-14 minecraft:dark_oak_fence
fill ~1 ~2 ~-15 ~3 ~2 ~-14 minecraft:dark_oak_slab
fill ~1 ~1 ~-16 ~3 ~1 ~-16 minecraft:dark_oak_stairs ["weirdo_direction":2]
fill ~1 ~1 ~-13 ~3 ~1 ~-13 minecraft:dark_oak_stairs ["weirdo_direction":3]
setblock ~1 ~3 ~-15 minecraft:sea_lantern
setblock ~3 ~3 ~-14 minecraft:sea_lantern
fill ~ ~1 ~-11 ~4 ~1 ~-11 minecraft:light_gray_carpet

# - lounge (south west) with fireplace and corner sofa
fill ~-10 ~1 ~-17 ~-6 ~4 ~-17 minecraft:polished_blackstone
fill ~-9 ~1 ~-17 ~-7 ~2 ~-17 minecraft:air
fill ~-9 ~1 ~-17 ~-7 ~1 ~-17 minecraft:campfire
fill ~-9 ~3 ~-17 ~-7 ~3 ~-17 minecraft:chiseled_quartz_block
fill ~-10 ~1 ~-15 ~-6 ~1 ~-12 minecraft:light_gray_carpet
fill ~-9 ~1 ~-14 ~-6 ~1 ~-14 minecraft:dark_oak_stairs ["weirdo_direction":3]
fill ~-10 ~1 ~-13 ~-10 ~1 ~-12 minecraft:dark_oak_stairs ["weirdo_direction":0]
setblock ~-6 ~1 ~-15 minecraft:jukebox
setblock ~-7 ~1 ~-11 minecraft:flower_pot
setblock ~-10 ~1 ~-11 minecraft:flower_pot

# - entrance hall
fill ~-4 ~1 ~-17 ~-2 ~1 ~-11 minecraft:red_carpet
setblock ~-5 ~1 ~-11 minecraft:flower_pot
setblock ~-2 ~1 ~-11 minecraft:red_carpet
fill ~-4 ~4 ~-15 ~-3 ~4 ~-12 minecraft:sea_lantern

# - guest bathroom (north west), floor tiled at floor level so the door opens
fill ~-10 ~ ~-25 ~-7 ~ ~-22 minecraft:smooth_quartz
setblock ~-10 ~1 ~-25 minecraft:cauldron
setblock ~-10 ~1 ~-22 minecraft:cauldron
setblock ~-9 ~1 ~-25 minecraft:quartz_slab
setblock ~-7 ~1 ~-22 minecraft:quartz_stairs ["weirdo_direction":3,"upside_down_bit":false]
setblock ~-7 ~2 ~-25 minecraft:glass_pane

# - utility room / pantry (keep the cell behind the door clear)
fill ~-10 ~1 ~-19 ~-8 ~1 ~-19 minecraft:barrel
setblock ~-7 ~1 ~-19 minecraft:furnace

# staircase up to the first floor (east side of the hall, runs north)
fill ~-2 ~1 ~-19 ~-2 ~1 ~-19 minecraft:dark_oak_stairs ["weirdo_direction":3,"upside_down_bit":false]
fill ~-2 ~2 ~-20 ~-2 ~2 ~-20 minecraft:dark_oak_stairs ["weirdo_direction":3,"upside_down_bit":false]
fill ~-2 ~1 ~-20 ~-2 ~1 ~-20 minecraft:dark_oak_planks
fill ~-2 ~3 ~-21 ~-2 ~3 ~-21 minecraft:dark_oak_stairs ["weirdo_direction":3,"upside_down_bit":false]
fill ~-2 ~1 ~-21 ~-2 ~2 ~-21 minecraft:dark_oak_planks
fill ~-2 ~4 ~-22 ~-2 ~4 ~-22 minecraft:dark_oak_stairs ["weirdo_direction":3,"upside_down_bit":false]
fill ~-2 ~1 ~-22 ~-2 ~3 ~-22 minecraft:dark_oak_planks
fill ~-2 ~5 ~-23 ~-2 ~5 ~-23 minecraft:dark_oak_stairs ["weirdo_direction":3,"upside_down_bit":false]
fill ~-2 ~1 ~-23 ~-2 ~4 ~-23 minecraft:dark_oak_planks

# stairwell opening through the first floor slab (top step stays in place)
fill ~-2 ~5 ~-22 ~-2 ~5 ~-19 minecraft:air
