# Upper floor: master suite, guest room, library, spa bathroom
# generated by tools/build_functions.py -- do not edit by hand


# partitions
fill ~-6 ~6 ~-25 ~-6 ~9 ~-19 minecraft:quartz_block
fill ~-1 ~6 ~-25 ~-1 ~9 ~-19 minecraft:quartz_block
fill ~-1 ~6 ~-22 ~-1 ~7 ~-21 minecraft:air

# the west wing is entered from the landing, next to the stair head
setblock ~-6 ~6 ~-25 minecraft:dark_oak_door ["direction":0,"door_hinge_bit":false,"open_bit":false,"upper_block_bit":false]
setblock ~-6 ~7 ~-25 minecraft:dark_oak_door ["direction":0,"door_hinge_bit":false,"open_bit":false,"upper_block_bit":true]

# bedroom wing divider
fill ~-1 ~6 ~-17 ~-1 ~9 ~-11 minecraft:quartz_block
fill ~-1 ~6 ~-15 ~-1 ~7 ~-14 minecraft:air

# - master bedroom (whole south west side)
fill ~-10 ~6 ~-17 ~-2 ~6 ~-11 minecraft:light_gray_carpet
fill ~-9 ~6 ~-15 ~-6 ~6 ~-12 minecraft:dark_oak_planks
setblock ~-8 ~6 ~-14 minecraft:bed ["direction":0,"head_piece_bit":false]
setblock ~-8 ~6 ~-13 minecraft:bed ["direction":0,"head_piece_bit":true]
setblock ~-7 ~6 ~-14 minecraft:bed ["direction":0,"head_piece_bit":false]
setblock ~-7 ~6 ~-13 minecraft:bed ["direction":0,"head_piece_bit":true]
setblock ~-10 ~6 ~-14 minecraft:barrel
setblock ~-10 ~7 ~-14 minecraft:lantern
setblock ~-5 ~6 ~-14 minecraft:barrel
setblock ~-5 ~7 ~-14 minecraft:lantern

# dresser + wall mounted screen, clear of the corridor at x11-x12
fill ~-10 ~6 ~-17 ~-10 ~7 ~-17 minecraft:chest
fill ~-8 ~7 ~-17 ~-5 ~8 ~-17 minecraft:black_concrete
setblock ~-3 ~6 ~-11 minecraft:flower_pot

# - spa bathroom (north west), sunken jacuzzi with a walkway at x8
fill ~-10 ~5 ~-25 ~-7 ~5 ~-19 minecraft:smooth_quartz
fill ~-10 ~6 ~-24 ~-8 ~6 ~-24 minecraft:quartz_block
fill ~-10 ~6 ~-22 ~-8 ~6 ~-22 minecraft:quartz_block
fill ~-10 ~6 ~-24 ~-10 ~6 ~-22 minecraft:quartz_block
fill ~-8 ~6 ~-24 ~-8 ~6 ~-22 minecraft:quartz_block
setblock ~-9 ~6 ~-23 minecraft:water
setblock ~-10 ~6 ~-25 minecraft:cauldron
setblock ~-9 ~6 ~-25 minecraft:quartz_slab
setblock ~-10 ~8 ~-23 minecraft:sea_lantern

# - walk in wardrobe, entered along the x8 walkway
fill ~-10 ~6 ~-19 ~-8 ~7 ~-19 minecraft:chest
setblock ~-10 ~6 ~-20 minecraft:barrel

# - library / office (north east)
fill ~ ~6 ~-25 ~4 ~8 ~-25 minecraft:bookshelf
fill ~4 ~6 ~-24 ~4 ~8 ~-22 minecraft:bookshelf
setblock ~ ~6 ~-24 minecraft:enchanting_table
fill ~1 ~6 ~-21 ~3 ~6 ~-21 minecraft:dark_oak_planks
setblock ~2 ~6 ~-20 minecraft:dark_oak_stairs ["weirdo_direction":3]
setblock ~1 ~7 ~-21 minecraft:lantern
fill ~ ~6 ~-19 ~4 ~6 ~-19 minecraft:light_gray_carpet

# - guest bedroom (south east)
fill ~ ~6 ~-17 ~4 ~6 ~-11 minecraft:light_gray_carpet
fill ~1 ~6 ~-15 ~3 ~6 ~-13 minecraft:dark_oak_planks
setblock ~2 ~6 ~-14 minecraft:bed ["direction":0,"head_piece_bit":false]
setblock ~2 ~6 ~-13 minecraft:bed ["direction":0,"head_piece_bit":true]
setblock ~1 ~6 ~-14 minecraft:barrel
setblock ~1 ~7 ~-14 minecraft:lantern
setblock ~4 ~6 ~-11 minecraft:chest
setblock ~ ~6 ~-11 minecraft:flower_pot

# landing at the top of the lower flight, and the corridor south
fill ~-5 ~6 ~-25 ~-2 ~6 ~-24 minecraft:red_carpet
fill ~-4 ~6 ~-23 ~-3 ~6 ~-18 minecraft:red_carpet

# upper flight to the roof terrace (west side of the hall, runs south)
fill ~-5 ~6 ~-23 ~-5 ~6 ~-23 minecraft:dark_oak_stairs ["weirdo_direction":2,"upside_down_bit":false]
fill ~-5 ~7 ~-22 ~-5 ~7 ~-22 minecraft:dark_oak_stairs ["weirdo_direction":2,"upside_down_bit":false]
fill ~-5 ~6 ~-22 ~-5 ~6 ~-22 minecraft:dark_oak_planks
fill ~-5 ~8 ~-21 ~-5 ~8 ~-21 minecraft:dark_oak_stairs ["weirdo_direction":2,"upside_down_bit":false]
fill ~-5 ~6 ~-21 ~-5 ~7 ~-21 minecraft:dark_oak_planks
fill ~-5 ~9 ~-20 ~-5 ~9 ~-20 minecraft:dark_oak_stairs ["weirdo_direction":2,"upside_down_bit":false]
fill ~-5 ~6 ~-20 ~-5 ~8 ~-20 minecraft:dark_oak_planks
fill ~-5 ~10 ~-19 ~-5 ~10 ~-19 minecraft:dark_oak_stairs ["weirdo_direction":2,"upside_down_bit":false]
fill ~-5 ~6 ~-19 ~-5 ~9 ~-19 minecraft:dark_oak_planks

# stairwell opening through the roof deck (top step stays in place)
fill ~-5 ~10 ~-23 ~-5 ~10 ~-20 minecraft:air
