# Lighting pass: recessed ceiling lights everywhere
# generated by tools/build_functions.py -- do not edit by hand


# ground floor ceiling lights (kept clear of the stairwell shafts)
setblock ~-9 ~5 ~-24 minecraft:sea_lantern
setblock ~-9 ~5 ~-20 minecraft:sea_lantern
setblock ~-9 ~5 ~-16 minecraft:sea_lantern
setblock ~-9 ~5 ~-12 minecraft:sea_lantern
setblock ~1 ~5 ~-24 minecraft:sea_lantern
setblock ~1 ~5 ~-20 minecraft:sea_lantern
setblock ~1 ~5 ~-16 minecraft:sea_lantern
setblock ~1 ~5 ~-12 minecraft:sea_lantern
setblock ~4 ~5 ~-24 minecraft:sea_lantern
setblock ~4 ~5 ~-20 minecraft:sea_lantern
setblock ~4 ~5 ~-16 minecraft:sea_lantern
setblock ~4 ~5 ~-12 minecraft:sea_lantern
setblock ~-4 ~5 ~-24 minecraft:sea_lantern
setblock ~-4 ~5 ~-14 minecraft:sea_lantern

# upper floor ceiling lights
setblock ~-9 ~10 ~-24 minecraft:sea_lantern
setblock ~-9 ~10 ~-20 minecraft:sea_lantern
setblock ~-9 ~10 ~-16 minecraft:sea_lantern
setblock ~-9 ~10 ~-12 minecraft:sea_lantern
setblock ~1 ~10 ~-24 minecraft:sea_lantern
setblock ~1 ~10 ~-20 minecraft:sea_lantern
setblock ~1 ~10 ~-16 minecraft:sea_lantern
setblock ~1 ~10 ~-12 minecraft:sea_lantern
setblock ~4 ~10 ~-24 minecraft:sea_lantern
setblock ~4 ~10 ~-20 minecraft:sea_lantern
setblock ~4 ~10 ~-16 minecraft:sea_lantern
setblock ~4 ~10 ~-12 minecraft:sea_lantern
setblock ~-2 ~10 ~-24 minecraft:sea_lantern
setblock ~-2 ~10 ~-14 minecraft:sea_lantern

# porch and entrance lighting
setblock ~-5 ~4 ~-9 minecraft:sea_lantern
setblock ~-1 ~4 ~-9 minecraft:sea_lantern
setblock ~-5 ~9 ~-9 minecraft:sea_lantern
setblock ~-1 ~9 ~-9 minecraft:sea_lantern
