"""Expectations for the luxury-base engine tests, read from the add-on's structure.

Reads addon/behavior_pack/structures/pas/luxury_base.mcstructure with the
harness's own NBT reader (nbt.py) and blueprint_meta.js (entrance), and writes a
JS module for the test pack:

    export const HOUSE_EXPECT = {
      size: [sx, sy, sz], entrance: {x,y,z},
      palette: ["minecraft:air", ...],          // block names only
      cells: [..],                               // palette index per cell, -1 = structure void,
                                                 // flat index (x*sy + y)*sz + z
      doors: [{x,y,z,name,direction,upper,hinge}], beds: [{x,y,z,direction,head}],
      chests: [{x,y,z,items:{"minecraft:apple": 5}}],
      workBlocks: [{x,y,z,name}],               // crafting table, furnaces, ...
    }

Coordinates are canonical local cells (+x east, +z south, entrance south).
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import nbt

WORK = ("minecraft:crafting_table", "minecraft:furnace", "minecraft:blast_furnace", "minecraft:smoker",
        "minecraft:stonecutter_block", "minecraft:anvil", "minecraft:loom", "minecraft:smithing_table",
        "minecraft:cauldron", "minecraft:barrel", "minecraft:enchanting_table")


def build(structure: Path, meta_js: Path | None) -> dict:
    _, root = nbt.read(structure.read_bytes())
    size = [v.value for v in root["size"].items]
    sx, sy, sz = size
    st = root["structure"]
    pal_items = st["palette"]["default"]["block_palette"].items
    names = [p["name"].value for p in pal_items]
    states = [nbt.to_py(p["states"]) for p in pal_items]
    idx = [v.value for v in st["block_indices"].items[0].items]
    bpd = st["palette"]["default"].get("block_position_data") or nbt.Compound()

    def loc(i):
        x, rem = divmod(i, sy * sz)
        y, z = divmod(rem, sz)
        return {"x": x, "y": y, "z": z}

    doors, beds, chests, work = [], [], [], []
    for i, p in enumerate(idx):
        if p < 0:
            continue
        n, s = names[p], states[p]
        if n.endswith("_door") or n == "minecraft:wooden_door":
            doors.append({**loc(i), "name": n, "direction": s.get("direction"), "upper": bool(s.get("upper_block_bit")),
                          "hinge": bool(s.get("door_hinge_bit"))})
        elif n == "minecraft:bed":
            beds.append({**loc(i), "direction": s.get("direction"), "head": bool(s.get("head_piece_bit"))})
        elif n == "minecraft:chest":
            items: dict[str, int] = {}
            ent = bpd.get(str(i))
            if ent is not None and "block_entity_data" in ent:
                be = ent["block_entity_data"]
                for it in (be.get("Items").items if be.get("Items") is not None else []):
                    items[it["Name"].value] = items.get(it["Name"].value, 0) + it["Count"].value
            chests.append({**loc(i), "items": items})
        elif n in WORK:
            work.append({**loc(i), "name": n})
    entrance = None
    if meta_js and meta_js.is_file():
        m = re.search(r"entrance:\s*Object\.freeze\(\{\s*x:\s*(-?\d+),\s*y:\s*(-?\d+),\s*z:\s*(-?\d+)", meta_js.read_text())
        if m:
            entrance = {"x": int(m.group(1)), "y": int(m.group(2)), "z": int(m.group(3))}
        b = re.search(r"buildSeconds:\s*(\d+(?:\.\d+)?)", meta_js.read_text())
        build_seconds = float(b.group(1)) if b else None
    else:
        build_seconds = None
    return {"size": size, "entrance": entrance, "buildSeconds": build_seconds, "palette": names, "cells": idx,
            "doors": doors, "beds": beds, "chests": chests, "workBlocks": work}


def write_js(data: dict, out: Path) -> None:
    out.write_text("// GENERATED by tools/engine/house_expect.py at install time - do not edit\n"
                   f"export const HOUSE_EXPECT = {json.dumps(data, separators=(',', ':'))};\n", encoding="utf-8")


if __name__ == "__main__":
    import sys
    repo = Path(__file__).resolve().parents[2]
    d = build(repo / "addon/behavior_pack/structures/pas/luxury_base.mcstructure",
              repo / "addon/behavior_pack/scripts/house/blueprint_meta.js")
    print(json.dumps({k: v for k, v in d.items() if k not in ("cells", "palette")}, indent=1)[:3000])
    if len(sys.argv) > 1:
        write_js(d, Path(sys.argv[1]))
