"""Tiny scene graph that renders to both SVG (for previews) and Android VectorDrawable XML.
Only features VectorDrawable supports: paths, linear/radial gradients, group transforms, clip-paths."""
import math, itertools

def f(v):
    s = f"{v:.2f}".rstrip('0').rstrip('.')
    return '0' if s in ('-0', '', '-') else s

def pt(p): return f"{f(p[0])},{f(p[1])}"

class Lin:
    def __init__(s, x1, y1, x2, y2, stops): s.k='linear'; s.a=(x1,y1,x2,y2); s.stops=stops
class Rad:
    def __init__(s, cx, cy, r, stops): s.k='radial'; s.a=(cx,cy,r); s.stops=stops

class P:
    def __init__(s, d, fill, alpha=1.0, even_odd=False): s.d=d; s.fill=fill; s.alpha=alpha; s.eo=even_odd
class G:
    def __init__(s, children, tx=0, ty=0, sx=1, sy=None, rot=0, px=0, py=0, clip=None):
        s.ch=children; s.tx=tx; s.ty=ty; s.sx=sx; s.sy=sx if sy is None else sy; s.rot=rot; s.px=px; s.py=py; s.clip=clip

def hexa(c, a=1.0):
    c=c.lstrip('#'); return f"#{int(round(a*255)):02X}{c.upper()}"

# ---------- SVG ----------
_ids = itertools.count()
def svg(node, vb, size, extra_defs=''):
    defs=[]; body=_svg(node, defs)
    x,y,w,h = vb
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x} {y} {w} {h}" width="{size}" height="{size}">'
            f'<defs>{"".join(defs)}{extra_defs}</defs>{body}</svg>')

def _paint(fill, defs):
    if isinstance(fill, str): return fill if fill.startswith('#') else fill, 1.0
    i=f"g{next(_ids)}"
    stops=''.join(f'<stop offset="{o}" stop-color="{c}" stop-opacity="{a}"/>' for o,c,a in fill.stops)
    if fill.k=='linear':
        x1,y1,x2,y2=fill.a
        defs.append(f'<linearGradient id="{i}" gradientUnits="userSpaceOnUse" x1="{f(x1)}" y1="{f(y1)}" x2="{f(x2)}" y2="{f(y2)}">{stops}</linearGradient>')
    else:
        cx,cy,r=fill.a
        defs.append(f'<radialGradient id="{i}" gradientUnits="userSpaceOnUse" cx="{f(cx)}" cy="{f(cy)}" r="{f(r)}">{stops}</radialGradient>')
    return f"url(#{i})", 1.0

def _svg(n, defs):
    if isinstance(n, list): return ''.join(_svg(c, defs) for c in n)
    if isinstance(n, P):
        if isinstance(n.fill, tuple):  # (hex, alpha)
            col, a = n.fill; paint = col; op = a*n.alpha
        else:
            paint,_ = _paint(n.fill, defs); op = n.alpha
        rule = ' fill-rule="evenodd"' if n.eo else ''
        return f'<path d="{n.d}" fill="{paint}" fill-opacity="{f(op) if op<1 else 1}"{rule}/>'
    t = f"translate({f(n.tx+n.px)} {f(n.ty+n.py)}) rotate({f(n.rot)}) scale({f(n.sx)} {f(n.sy)}) translate({f(-n.px)} {f(-n.py)})"
    inner = _svg(n.ch, defs)
    if n.clip:
        i=f"c{next(_ids)}"; defs.append(f'<clipPath id="{i}"><path d="{n.clip}"/></clipPath>')
        inner = f'<g clip-path="url(#{i})">{inner}</g>'
    return f'<g transform="{t}">{inner}</g>'

# ---------- VectorDrawable ----------
def vd(node, vw, vh=None, wdp=None, hdp=None, vtx=0, vty=0):
    vh = vh or vw; wdp = wdp or vw; hdp = hdp or vh
    body = _vd(node, 1) if (vtx==0 and vty==0) else _vd(G([node], tx=vtx, ty=vty), 1)
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tools/logo/build_icons.py. Edit the script, not this file. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    xmlns:aapt="http://schemas.android.com/aapt"\n'
            f'    android:width="{f(wdp)}dp" android:height="{f(hdp)}dp"\n'
            f'    android:viewportWidth="{f(vw)}" android:viewportHeight="{f(vh)}">\n'
            f'{body}</vector>\n')

def _vd(n, depth):
    ind='    '*depth
    if isinstance(n, list): return ''.join(_vd(c, depth) for c in n)
    if isinstance(n, P):
        attrs=[f'android:pathData="{n.d}"']
        if n.eo: attrs.append('android:fillType="evenOdd"')
        if isinstance(n.fill, tuple):
            col,a = n.fill
            attrs.append(f'android:fillColor="{hexa(col, a*n.alpha)}"')
            return f'{ind}<path {" ".join(attrs)} />\n'
        if isinstance(n.fill, str):
            attrs.append(f'android:fillColor="{hexa(n.fill, n.alpha)}"')
            return f'{ind}<path {" ".join(attrs)} />\n'
        if n.alpha < 1: attrs.append(f'android:fillAlpha="{f(n.alpha)}"')
        g=n.fill
        if g.k=='linear':
            x1,y1,x2,y2=g.a; ga=f'android:type="linear" android:startX="{f(x1)}" android:startY="{f(y1)}" android:endX="{f(x2)}" android:endY="{f(y2)}"'
        else:
            cx,cy,r=g.a; ga=f'android:type="radial" android:centerX="{f(cx)}" android:centerY="{f(cy)}" android:gradientRadius="{f(r)}"'
        items=''.join(f'{ind}            <item android:offset="{f(o)}" android:color="{hexa(c,a)}" />\n' for o,c,a in g.stops)
        return (f'{ind}<path {" ".join(attrs)}>\n{ind}    <aapt:attr name="android:fillColor">\n'
                f'{ind}        <gradient {ga}>\n{items}{ind}        </gradient>\n{ind}    </aapt:attr>\n{ind}</path>\n')
    attrs=[]
    if n.tx or n.px: attrs.append(f'android:translateX="{f(n.tx)}"')
    if n.ty or n.py: attrs.append(f'android:translateY="{f(n.ty)}"')
    if n.sx!=1: attrs.append(f'android:scaleX="{f(n.sx)}"')
    if n.sy!=1: attrs.append(f'android:scaleY="{f(n.sy)}"')
    if n.rot: attrs.append(f'android:rotation="{f(n.rot)}"')
    if n.px: attrs.append(f'android:pivotX="{f(n.px)}"')
    if n.py: attrs.append(f'android:pivotY="{f(n.py)}"')
    head=f'{ind}<group{(" "+" ".join(attrs)) if attrs else ""}>\n'
    clip=f'{ind}    <clip-path android:pathData="{n.clip}" />\n' if n.clip else ''
    return head+clip+_vd(n.ch, depth+1)+f'{ind}</group>\n'

# ---------- shapes ----------
def catmull(pts):
    N=len(pts); d=f"M{pt(pts[0])}"
    for i in range(N):
        p0,p1,p2,p3=pts[(i-1)%N],pts[i],pts[(i+1)%N],pts[(i+2)%N]
        c1=(p1[0]+(p2[0]-p0[0])/6, p1[1]+(p2[1]-p0[1])/6)
        c2=(p2[0]-(p3[0]-p1[0])/6, p2[1]-(p3[1]-p1[1])/6)
        d+=f" C{pt(c1)} {pt(c2)} {pt(p2)}"
    return d+" Z"

def superellipse(cx, cy, a, b, n=3.0, segs=72, reverse=False):
    """Superellipse |x/a|^n + |y/b|^n = 1, as evenly spaced smooth curve segments (clockwise on screen)."""
    dense = []
    for i in range(4000):
        t = 2 * math.pi * i / 4000; c, s_ = math.cos(t), math.sin(t)
        dense.append((cx + a * math.copysign(abs(c) ** (2 / n), c), cy + b * math.copysign(abs(s_) ** (2 / n), s_)))
    lengths = [0.0]
    for i in range(1, len(dense) + 1):
        p0, p1 = dense[i - 1], dense[i % len(dense)]
        lengths.append(lengths[-1] + math.hypot(p1[0] - p0[0], p1[1] - p0[1]))
    total, pts, j = lengths[-1], [], 0
    for k in range(segs):
        target = total * k / segs
        while lengths[j + 1] < target: j += 1
        p0, p1 = dense[j], dense[(j + 1) % len(dense)]
        u = (target - lengths[j]) / max(lengths[j + 1] - lengths[j], 1e-9)
        pts.append((p0[0] + (p1[0] - p0[0]) * u, p0[1] + (p1[1] - p0[1]) * u))
    if reverse: pts = pts[::-1]
    return catmull(pts)

def ellipse(cx, cy, rx, ry, reverse=False):
    sw = 0 if reverse else 1
    return (f"M{f(cx-rx)},{f(cy)} A{f(rx)},{f(ry)} 0 0 {sw} {f(cx+rx)},{f(cy)} "
            f"A{f(rx)},{f(ry)} 0 0 {sw} {f(cx-rx)},{f(cy)} Z")

def circle(cx, cy, r, reverse=False): return ellipse(cx, cy, r, r, reverse)

def rrect(x, y, w, h, r, reverse=False):
    if r == 0:
        return (f"M{f(x)},{f(y)} H{f(x+w)} V{f(y+h)} H{f(x)} Z" if not reverse
                else f"M{f(x)},{f(y)} V{f(y+h)} H{f(x+w)} V{f(y)} Z")
    if not reverse:
        return (f"M{f(x+r)},{f(y)} H{f(x+w-r)} A{f(r)},{f(r)} 0 0 1 {f(x+w)},{f(y+r)} V{f(y+h-r)} "
                f"A{f(r)},{f(r)} 0 0 1 {f(x+w-r)},{f(y+h)} H{f(x+r)} A{f(r)},{f(r)} 0 0 1 {f(x)},{f(y+h-r)} "
                f"V{f(y+r)} A{f(r)},{f(r)} 0 0 1 {f(x+r)},{f(y)} Z")
    return (f"M{f(x+r)},{f(y)} A{f(r)},{f(r)} 0 0 0 {f(x)},{f(y+r)} V{f(y+h-r)} A{f(r)},{f(r)} 0 0 0 {f(x+r)},{f(y+h)} "
            f"H{f(x+w-r)} A{f(r)},{f(r)} 0 0 0 {f(x+w)},{f(y+h-r)} V{f(y+r)} A{f(r)},{f(r)} 0 0 0 {f(x+w-r)},{f(y)} Z")

def band(cx, cy, R, t, a1, a2, reverse=False):
    """Arc-shaped band (a smile) with round ends, angles in degrees, y down."""
    ro, ri, h = R+t/2, R-t/2, t/2
    P_=lambda r,a:(cx+r*math.cos(math.radians(a)), cy+r*math.sin(math.radians(a)))
    o1,o2,i1,i2=P_(ro,a1),P_(ro,a2),P_(ri,a1),P_(ri,a2)
    large = 1 if abs(a2-a1) > 180 else 0
    if not reverse:
        return (f"M{pt(o1)} A{f(ro)},{f(ro)} 0 {large} 1 {pt(o2)} A{f(h)},{f(h)} 0 0 1 {pt(i2)} "
                f"A{f(ri)},{f(ri)} 0 {large} 0 {pt(i1)} A{f(h)},{f(h)} 0 0 1 {pt(o1)} Z")
    return (f"M{pt(o1)} A{f(h)},{f(h)} 0 0 0 {pt(i1)} A{f(ri)},{f(ri)} 0 {large} 1 {pt(i2)} "
            f"A{f(h)},{f(h)} 0 0 0 {pt(o2)} A{f(ro)},{f(ro)} 0 {large} 0 {pt(o1)} Z")

def sparkle(cx, cy, rx, ry, k=0.22, reverse=False):
    top=(cx,cy-ry); right=(cx+rx,cy); bot=(cx,cy+ry); left=(cx-rx,cy)
    ctr=(cx+rx*k,cy-ry*k); cbr=(cx+rx*k,cy+ry*k); cbl=(cx-rx*k,cy+ry*k); ctl=(cx-rx*k,cy-ry*k)
    if not reverse:
        return f"M{pt(top)} Q{pt(ctr)} {pt(right)} Q{pt(cbr)} {pt(bot)} Q{pt(cbl)} {pt(left)} Q{pt(ctl)} {pt(top)} Z"
    return f"M{pt(top)} Q{pt(ctl)} {pt(left)} Q{pt(cbl)} {pt(bot)} Q{pt(cbr)} {pt(right)} Q{pt(ctr)} {pt(top)} Z"

def translate_path(d, dx, dy):
    """Shift absolute path data (M L H V C Q A Z only, absolute)."""
    import re
    toks=re.findall(r'[A-Za-z]|-?\d*\.?\d+(?:e-?\d+)?', d); out=[]; i=0; cmd=None
    def num():
        nonlocal i; v=float(toks[i]); i+=1; return v
    while i<len(toks):
        if toks[i].isalpha(): cmd=toks[i]; i+=1; out.append(cmd)
        if cmd in 'Zz': continue
        if cmd in 'ML': x=num(); y=num(); out.append(pt((x+dx,y+dy)))
        elif cmd=='H': out.append(f(num()+dx))
        elif cmd=='V': out.append(f(num()+dy))
        elif cmd=='C': out.append(' '.join(pt((num()+dx,num()+dy)) for _ in range(3)))
        elif cmd=='Q': out.append(' '.join(pt((num()+dx,num()+dy)) for _ in range(2)))
        elif cmd=='A':
            rx=num(); ry=num(); rot=num(); la=int(num()); sw=int(num()); x=num(); y=num()
            out.append(f"{f(rx)},{f(ry)} {f(rot)} {la} {sw} {pt((x+dx,y+dy))}")
    return ' '.join(out)
