#!/usr/bin/env python3
"""Generate GUIDE.md: file tree, full source of every text file, install + test steps.

Everything that is code is embedded straight from the files on disk, so the guide
can never drift from what is inside SCP-096.mcaddon.
"""
import base64
import hashlib
import json
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADDON = ROOT / "SCP-096.mcaddon"
OUT = ROOT / "GUIDE.md"

TEXT_EXT = {".json", ".js", ".lang"}
LANG_OF = {".json": "json", ".js": "javascript", ".lang": "properties"}
MAX_B64 = 40_000  # embed a PNG as base64 only if it is smaller than this


def pack_files():
    files = []
    for pack in ("SCP096_BP", "SCP096_RP"):
        for p in sorted((ROOT / pack).rglob("*")):
            if p.is_file():
                files.append(p)
    return files


def tree(files):
    lines = ["SCP-096.mcaddon (a zip file)"]
    by_pack = {}
    for p in files:
        rel = p.relative_to(ROOT)
        by_pack.setdefault(rel.parts[0], []).append(rel)
    for pack, rels in by_pack.items():
        lines.append(f"├── {pack}/")
        dirs_seen = set()
        for rel in rels:
            parts = rel.parts[1:]
            for i in range(len(parts) - 1):
                d = "/".join(parts[: i + 1])
                if d not in dirs_seen:
                    dirs_seen.add(d)
                    lines.append("│   " + "    " * i + f"├── {parts[i]}/")
            size = (ROOT / rel).stat().st_size
            lines.append("│   " + "    " * (len(parts) - 1) + f"├── {parts[-1]}  ({size:,} bytes)")
    return "\n".join(lines)


def fence(lang, text):
    f = "````" if "```" in text else "```"
    return f"{f}{lang}\n{text.rstrip()}\n{f}"


def main():
    files = pack_files()
    parts = []
    parts.append(Path(ROOT / "tools" / "guide_head.md").read_text(encoding="utf-8"))
    parts.append("## 1. Folder and file list\n\n" + fence("text", tree(files)))
    if ADDON.exists():
        with zipfile.ZipFile(ADDON) as z:
            names = sorted(n for n in z.namelist() if not n.endswith("/"))
        sha = hashlib.sha256(ADDON.read_bytes()).hexdigest()
        parts.append(
            f"`SCP-096.mcaddon` = {ADDON.stat().st_size:,} bytes, {len(names)} files, sha256 `{sha}`."
        )

    parts.append("## 2. Full code of every file\n")
    for p in files:
        rel = p.relative_to(ROOT).as_posix()
        ext = p.suffix.lower()
        parts.append(f"### `{rel}`\n")
        if ext in TEXT_EXT:
            parts.append(fence(LANG_OF[ext], p.read_text(encoding="utf-8")))
        elif ext == ".png":
            data = p.read_bytes()
            parts.append(f"Binary PNG, {len(data):,} bytes, sha256 `{hashlib.sha256(data).hexdigest()}`. "
                         "Generated by `tools/make_texture.py` / `tools/make_model.py`.")
            if len(data) < MAX_B64:
                b64 = base64.b64encode(data).decode()
                parts.append("<details><summary>base64 of the PNG (decode to rebuild the file)</summary>\n\n"
                             + fence("text", "\n".join(b64[i:i + 100] for i in range(0, len(b64), 100)))
                             + "\n\n</details>")
        elif ext == ".ogg":
            data = p.read_bytes()
            parts.append(f"Binary OGG Vorbis (mono, 44.1 kHz), {len(data):,} bytes, sha256 `{hashlib.sha256(data).hexdigest()}`. "
                         "Synthesised by `tools/make_sounds.py`.")
        else:
            parts.append(f"(binary, {p.stat().st_size:,} bytes)")
        parts.append("")

    parts.append(Path(ROOT / "tools" / "guide_tail.md").read_text(encoding="utf-8"))
    OUT.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    sys.exit(main())
