# Build the whole luxury mansion around the player
# generated by tools/build_functions.py -- do not edit by hand

tellraw @s {"rawtext":[{"text":"§6[Luxury House] §fBuilding your mansion..."}]}

function lux/parts/01_site
function lux/parts/02_shell
function lux/parts/03_glass
function lux/parts/04_ground_floor
function lux/parts/05_upper_floor
function lux/parts/06_roof
function lux/parts/07_pool
function lux/parts/08_grounds
function lux/parts/09_lighting

function lux/done
