# Remove the mansion and flatten the plot again
# generated by tools/build_functions.py -- do not edit by hand

tellraw @s {"rawtext":[{"text":"§6[Luxury House] §fClearing the plot..."}]}
fill ~-15 ~ ~-31 ~15 ~18 ~-1 minecraft:air
fill ~-15 ~-7 ~-31 ~15 ~-2 ~-1 minecraft:dirt
fill ~-15 ~-1 ~-31 ~15 ~-1 ~-1 minecraft:grass_block
tellraw @s {"rawtext":[{"text":"§6[Luxury House] §aPlot cleared."}]}
