# Finishing touches and the welcome message
# generated by tools/build_functions.py -- do not edit by hand

titleraw @s title {"rawtext":[{"text":"§6Luxury House"}]}
titleraw @s subtitle {"rawtext":[{"text":"§fYour mansion is ready"}]}
playsound random.levelup @s ~ ~ ~ 1 1
tellraw @s {"rawtext":[{"text":"§6[Luxury House] §aDone! §fThe front door is right in front of you."}]}
tellraw @s {"rawtext":[{"text":"§7Pool on the east side, roof terrace up the stairs. Remove it again with §f/function lux/clear"}]}
