# How to use the pack
# generated by tools/build_functions.py -- do not edit by hand

tellraw @s {"rawtext":[{"text":"§6=== Luxury House ==="}]}
tellraw @s {"rawtext":[{"text":"§f/function lux/build §7- build the mansion around you"}]}
tellraw @s {"rawtext":[{"text":"§f/function lux/clear §7- remove it again"}]}
tellraw @s {"rawtext":[{"text":"§f/function lux/help  §7- show this list"}]}
tellraw @s {"rawtext":[{"text":"§7Stand on flat ground, face north, leave about 31x31 blocks free."}]}
tellraw @s {"rawtext":[{"text":"§7The house is built in front of you, the pool on your right."}]}
