// @ts-check
// GENERATED by tools/house/blueprint.py — do not edit by hand.
// Geometry of the Luxury Base structure in its canonical orientation
// (+x east, +z south, +y up; entrance on the SOUTH side).

/**
 * @typedef {{ x: number, y: number, z: number }} Vec3i
 * @typedef {{
 *   structureId: string,
 *   size: Vec3i,
 *   entrance: Vec3i,
 *   entranceSide: "south",
 *   floorY: number,
 *   supportRatio: number,
 *   buildSeconds: number,
 *   probeCell: Vec3i,
 * }} HouseMeta
 */

/**
 * - `structureId`: id of `structures/pas/luxury_base.mcstructure`.
 * - `size`: structure size in blocks (x, y, z).
 * - `entrance`: local cell just OUTSIDE the front door, where the player stands
 *   (porch, in front of the east door leaf); `y` is the walking level.
 * - `entranceSide`: side of the box the front door faces in canonical orientation.
 * - `floorY`: local y of the ground-floor walking surface (feet level); local y 0 is
 *   the foundation layer that sits on top of the terrain.
 * - `supportRatio`: minimum fraction of footprint cells that must have solid ground below.
 * - `buildSeconds`: animationSeconds for the layer-by-layer placement.
 * - `probeCell`: a local cell that is plain air in the finished house (living room,
 *   under the ceiling) — safe scratch cell for the rotation calibration probe.
 * @type {Readonly<HouseMeta>}
 */
export const HOUSE = Object.freeze({
  structureId: "pas:luxury_base",
  size: Object.freeze({ x: 18, y: 13, z: 15 }),
  entrance: Object.freeze({ x: 9, y: 1, z: 12 }),
  entranceSide: "south",
  floorY: 1,
  supportRatio: 0.8,
  buildSeconds: 7,
  probeCell: Object.freeze({ x: 1, y: 4, z: 6 }),
});
