#!/usr/bin/env python3
"""Generate the .mcfunction files that build the Luxury House.

The house is described here in plain local coordinates:

    x : 0 .. 30   west  -> east
    z : 0 .. 30   north -> south   (the player stands south of the plot)
    y : 0         top surface of the house podium / ground floor level

Local coordinates are emitted as tilde (~) coordinates relative to the player,
so the whole mansion is built around whoever runs `/function lux/build`.

Run:  python3 tools/build_functions.py
"""

import os
import shutil

# --- plot geometry -----------------------------------------------------------

PLOT_X = (0, 30)
PLOT_Z = (0, 30)

# House shell (outer wall line)
HX1, HX2 = 4, 20
HZ1, HZ2 = 5, 21
# Interior of the shell
IX1, IX2 = HX1 + 1, HX2 - 1
IZ1, IZ2 = HZ1 + 1, HZ2 - 1

Y_GROUND = -1          # grass / yard surface block
Y_F1 = 0               # ground floor slab (walk on top of it, at y=1)
Y_F2 = 5               # first floor slab / ground floor ceiling
Y_ROOF = 10            # roof deck / upper floor ceiling

# The player ends up standing just south of the plot, facing north.
OX, OY, OZ = -15, 0, -31

FUNC_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "behavior_packs", "luxury_house_bp", "functions", "lux",
)

# --- tiny command emitter ----------------------------------------------------


def _rel(value: int, offset: int) -> str:
    total = value + offset
    return "~" if total == 0 else "~%d" % total


def pos(x: int, y: int, z: int) -> str:
    return "%s %s %s" % (_rel(x, OX), _rel(y, OY), _rel(z, OZ))


def states(**kwargs) -> str:
    if not kwargs:
        return ""
    parts = []
    for key, value in kwargs.items():
        key = key.replace("__", ":")
        if isinstance(value, bool):
            parts.append('"%s":%s' % (key, "true" if value else "false"))
        elif isinstance(value, int):
            parts.append('"%s":%d' % (key, value))
        else:
            parts.append('"%s":"%s"' % (key, value))
    return " [%s]" % ",".join(parts)


class Part(object):
    """One .mcfunction file."""

    def __init__(self, name, title):
        self.name = name
        self.title = title
        self.lines = ["# %s" % title, "# generated by tools/build_functions.py -- do not edit by hand", ""]

    # -- primitives --
    def cmd(self, line):
        self.lines.append(line)

    def note(self, text):
        self.lines.append("")
        self.lines.append("# %s" % text)

    def fill(self, x1, y1, z1, x2, y2, z2, block, st="", mode=""):
        tail = (" " + mode) if mode else ""
        self.cmd("fill %s %s %s%s%s" % (pos(x1, y1, z1), pos(x2, y2, z2), block, st, tail))

    def block(self, x, y, z, block, st=""):
        self.cmd("setblock %s %s%s" % (pos(x, y, z), block, st))

    # -- helpers --
    def cuboid(self, x1, y1, z1, x2, y2, z2, block, st=""):
        self.fill(x1, y1, z1, x2, y2, z2, block, st)

    def walls(self, x1, z1, x2, z2, y1, y2, block, st=""):
        """Four vertical walls (hollow box without floor or ceiling)."""
        self.fill(x1, y1, z1, x2, y2, z1, block, st)
        self.fill(x1, y1, z2, x2, y2, z2, block, st)
        self.fill(x1, y1, z1, x1, y2, z2, block, st)
        self.fill(x2, y1, z1, x2, y2, z2, block, st)

    def outline(self, x1, z1, x2, z2, y, block, st=""):
        self.walls(x1, z1, x2, z2, y, y, block, st)

    def row(self, coords, y, block, st=""):
        for x, z in coords:
            self.block(x, y, z, block, st)

    def door(self, x, y, z, wood="dark_oak", direction=1):
        """Place both halves of a door. direction 0=E 1=S 2=W 3=N."""
        base = "minecraft:%s_door" % wood
        self.block(x, y, z, base, states(direction=direction, door_hinge_bit=False,
                                         open_bit=False, upper_block_bit=False))
        self.block(x, y + 1, z, base, states(direction=direction, door_hinge_bit=False,
                                             open_bit=False, upper_block_bit=True))

    def bed(self, x, y, z, direction=0):
        """direction 0=S 1=W 2=N 3=E -- head is one block that way."""
        dx, dz = {0: (0, 1), 1: (-1, 0), 2: (0, -1), 3: (1, 0)}[direction]
        self.block(x, y, z, "minecraft:bed", states(direction=direction, head_piece_bit=False))
        self.block(x + dx, y, z + dz, "minecraft:bed", states(direction=direction, head_piece_bit=True))

    def stairs(self, x, y, z, block, facing, upside_down=False):
        """facing 0=E 1=W 2=S 3=N (Bedrock weirdo_direction)."""
        self.block(x, y, z, block, states(weirdo_direction=facing, upside_down_bit=upside_down))

    def stairs_run(self, x1, x2, z, y, block, facing, upside_down=False):
        self.fill(x1, y, z, x2, y, z, block,
                  states(weirdo_direction=facing, upside_down_bit=upside_down))

    def tree(self, x, z, y=Y_GROUND, height=5, log="minecraft:oak_log", leaf="minecraft:oak_leaves"):
        top = y + height
        self.fill(x, y + 1, z, x, top, z, log)
        self.fill(x - 2, top - 2, z - 2, x + 2, top - 1, z + 2, leaf, "", "keep")
        self.fill(x - 1, top, z - 1, x + 1, top, z + 1, leaf, "", "keep")
        self.block(x, top + 1, z, leaf)
        self.fill(x, y + 1, z, x, top, z, log)

    def lamp(self, x, z, y=Y_GROUND):
        self.fill(x, y + 1, z, x, y + 3, z, "minecraft:quartz_pillar")
        self.block(x, y + 4, z, "minecraft:sea_lantern")

    def write(self, directory):
        path = os.path.join(directory, "%s.mcfunction" % self.name)
        with open(path, "w") as handle:
            handle.write("\n".join(self.lines).rstrip() + "\n")
        return path, sum(1 for line in self.lines if line and not line.startswith("#"))


PARTS = []


def part(name, title):
    p = Part(name, title)
    PARTS.append(p)
    return p


# =============================================================================
# 01 - site: clear the area, lay the lawn, pour the podium
# =============================================================================
p = part("parts/01_site", "Site preparation: clear the plot, lawn, foundation podium")
p.note("wipe everything that was standing on the plot")
p.fill(PLOT_X[0], Y_GROUND + 1, PLOT_Z[0], PLOT_X[1], Y_ROOF + 8, PLOT_Z[1], "minecraft:air")
p.note("solid ground under the whole plot")
p.fill(PLOT_X[0], Y_GROUND - 6, PLOT_Z[0], PLOT_X[1], Y_GROUND - 1, PLOT_Z[1], "minecraft:stone")
p.fill(PLOT_X[0], Y_GROUND, PLOT_Z[0], PLOT_X[1], Y_GROUND, PLOT_Z[1], "minecraft:grass_block")

p.note("raised podium the mansion sits on (front porch included)")
p.fill(HX1 - 1, Y_F1, HZ1 - 1, HX2 + 1, Y_F1, HZ2 + 2, "minecraft:smooth_quartz")
p.fill(HX1 - 1, Y_GROUND, HZ1 - 1, HX2 + 1, Y_GROUND, HZ2 + 2, "minecraft:polished_blackstone")

p.note("polished floor inside the ground floor")
p.fill(IX1, Y_F1, IZ1, IX2, Y_F1, IZ2, "minecraft:quartz_block")

p.note("entrance steps up to the porch")
p.stairs_run(11, 13, HZ2 + 3, Y_F1, "minecraft:quartz_stairs", 2)

# =============================================================================
# 02 - shell: outer walls, slabs, columns
# =============================================================================
p = part("parts/02_shell", "Shell: exterior walls, floor slabs and columns")

p.note("ground floor walls")
p.walls(HX1, HZ1, HX2, HZ2, Y_F1 + 1, Y_F2 - 1, "minecraft:white_concrete")
p.note("dark trim band at the top of the ground floor")
p.outline(HX1, HZ1, HX2, HZ2, Y_F2 - 1, "minecraft:polished_blackstone")

p.note("first floor slab (= ground floor ceiling) + overhang")
p.fill(HX1 - 1, Y_F2, HZ1 - 1, HX2 + 1, Y_F2, HZ2 + 2, "minecraft:smooth_quartz")
p.fill(IX1, Y_F2, IZ1, IX2, Y_F2, IZ2, "minecraft:quartz_block")

p.note("upper floor walls")
p.walls(HX1, HZ1, HX2, HZ2, Y_F2 + 1, Y_ROOF - 1, "minecraft:white_concrete")
p.outline(HX1, HZ1, HX2, HZ2, Y_ROOF - 1, "minecraft:polished_blackstone")

p.note("roof deck + overhang lip")
p.fill(HX1 - 1, Y_ROOF, HZ1 - 1, HX2 + 1, Y_ROOF, HZ2 + 2, "minecraft:smooth_quartz")
p.fill(IX1, Y_ROOF, IZ1, IX2, Y_ROOF, IZ2, "minecraft:quartz_block")

p.note("corner columns run the full height")
for cx in (HX1, HX2):
    for cz in (HZ1, HZ2):
        p.fill(cx, Y_F1 + 1, cz, cx, Y_ROOF - 1, cz, "minecraft:quartz_pillar")

p.note("porch columns holding the balcony")
for cx in (5, 9, 15, 19):
    p.fill(cx, Y_F1 + 1, HZ2 + 2, cx, Y_F2 - 1, HZ2 + 2, "minecraft:quartz_pillar")
    p.block(cx, Y_F2 - 1, HZ2 + 2, "minecraft:chiseled_quartz_block")

p.note("gold cornice detail")
for cx in (HX1 - 1, HX2 + 1):
    for cz in (HZ1 - 1, HZ2 + 2):
        p.block(cx, Y_ROOF, cz, "minecraft:gold_block")

# =============================================================================
# 03 - glazing: windows, doors, balcony
# =============================================================================
p = part("parts/03_glass", "Glazing: floor to ceiling windows, doors, balcony")

p.note("ground floor front windows")
p.fill(6, Y_F1 + 2, HZ2, 10, Y_F1 + 3, HZ2, "minecraft:glass")
p.fill(14, Y_F1 + 2, HZ2, 18, Y_F1 + 3, HZ2, "minecraft:glass")
p.note("front entrance: double doors under a gold arch")
p.fill(11, Y_F1 + 1, HZ2, 13, Y_F1 + 3, HZ2, "minecraft:air")
p.fill(11, Y_F1 + 3, HZ2, 13, Y_F1 + 3, HZ2, "minecraft:gold_block")
p.door(11, Y_F1 + 1, HZ2, direction=1)
p.door(12, Y_F1 + 1, HZ2, direction=1)
p.block(13, Y_F1 + 1, HZ2, "minecraft:glass")
p.block(13, Y_F1 + 2, HZ2, "minecraft:glass")

p.note("east side glass wall facing the pool + patio door")
p.fill(HX2, Y_F1 + 2, 14, HX2, Y_F1 + 3, 20, "minecraft:glass")
p.fill(HX2, Y_F1 + 1, 16, HX2, Y_F1 + 2, 17, "minecraft:air")
p.door(HX2, Y_F1 + 1, 16, direction=0)
p.door(HX2, Y_F1 + 1, 17, direction=0)

p.note("west and north ground floor windows")
p.fill(HX1, Y_F1 + 2, 14, HX1, Y_F1 + 3, 19, "minecraft:glass")
p.fill(14, Y_F1 + 2, HZ1, 18, Y_F1 + 3, HZ1, "minecraft:glass")
p.fill(6, Y_F1 + 2, HZ1, 9, Y_F1 + 3, HZ1, "minecraft:glass")

p.note("upper floor: panoramic glazing")
p.fill(6, Y_F2 + 1, HZ2, 18, Y_F2 + 3, HZ2, "minecraft:glass")
p.fill(HX2, Y_F2 + 1, 7, HX2, Y_F2 + 3, 19, "minecraft:glass")
p.fill(HX1, Y_F2 + 1, 7, HX1, Y_F2 + 3, 19, "minecraft:glass")
p.fill(6, Y_F2 + 1, HZ1, 18, Y_F2 + 2, HZ1, "minecraft:glass")

p.note("balcony over the porch + doors out to it")
p.fill(HX1 + 1, Y_F2, HZ2 + 1, HX2 - 1, Y_F2, HZ2 + 2, "minecraft:smooth_quartz")
p.fill(11, Y_F2 + 1, HZ2, 13, Y_F2 + 2, HZ2, "minecraft:air")
p.door(11, Y_F2 + 1, HZ2, direction=1)
p.door(12, Y_F2 + 1, HZ2, direction=1)
p.block(13, Y_F2 + 1, HZ2, "minecraft:glass")
p.block(13, Y_F2 + 2, HZ2, "minecraft:glass")
p.note("balcony railing")
p.fill(HX1 + 1, Y_F2 + 1, HZ2 + 2, HX2 - 1, Y_F2 + 1, HZ2 + 2, "minecraft:glass_pane")
p.fill(HX1 + 1, Y_F2 + 1, HZ2 + 1, HX1 + 1, Y_F2 + 1, HZ2 + 2, "minecraft:glass_pane")
p.fill(HX2 - 1, Y_F2 + 1, HZ2 + 1, HX2 - 1, Y_F2 + 1, HZ2 + 2, "minecraft:glass_pane")

# =============================================================================
# 04 - ground floor: kitchen, dining, living room, hall, guest bathroom
# =============================================================================
p = part("parts/04_ground_floor", "Ground floor: kitchen, dining, lounge, hall, guest bath")

p.note("interior partitions (open plan, so only where it matters)")
p.fill(9, Y_F1 + 1, IZ1, 9, Y_F1 + 4, 12, "minecraft:quartz_block")
p.fill(14, Y_F1 + 1, IZ1, 14, Y_F1 + 4, 12, "minecraft:quartz_block")
p.fill(14, Y_F1 + 1, 9, 14, Y_F1 + 2, 10, "minecraft:air")
p.door(9, Y_F1 + 1, 8, direction=0)
p.door(9, Y_F1 + 1, 11, direction=0)
p.note("guest bath / utility divider")
p.fill(IX1, Y_F1 + 1, 10, 8, Y_F1 + 4, 10, "minecraft:quartz_block")
p.door(6, Y_F1 + 1, 10, direction=1)
p.note("kitchen / dining divider")
p.fill(15, Y_F1 + 1, 13, IX2, Y_F1 + 4, 13, "minecraft:quartz_block")
p.fill(16, Y_F1 + 1, 13, 17, Y_F1 + 2, 13, "minecraft:air")

p.note("- kitchen (north east)")
p.fill(15, Y_F1 + 1, IZ1, IX2, Y_F1 + 1, IZ1, "minecraft:smooth_quartz")
p.block(16, Y_F1 + 1, IZ1, "minecraft:blast_furnace")
p.block(17, Y_F1 + 1, IZ1, "minecraft:smoker")
p.block(18, Y_F1 + 1, IZ1, "minecraft:cauldron")
p.fill(IX2, Y_F1 + 1, 7, IX2, Y_F1 + 1, 9, "minecraft:smooth_quartz")
p.block(IX2, Y_F1 + 1, 8, "minecraft:crafting_table")
p.block(IX2, Y_F1 + 1, 11, "minecraft:barrel")
p.block(15, Y_F1 + 1, 7, "minecraft:chest")
p.block(15, Y_F1 + 1, 8, "minecraft:chest")
p.note("kitchen island with bar stools")
p.fill(16, Y_F1 + 1, 10, 18, Y_F1 + 1, 10, "minecraft:quartz_block")
p.fill(16, Y_F1 + 2, 10, 18, Y_F1 + 2, 10, "minecraft:quartz_slab")
p.stairs(16, Y_F1 + 1, 12, "minecraft:dark_oak_stairs", 3)
p.stairs(18, Y_F1 + 1, 12, "minecraft:dark_oak_stairs", 3)

p.note("- dining room (south east)")
p.fill(16, Y_F1 + 1, 16, 18, Y_F1 + 1, 17, "minecraft:dark_oak_fence")
p.fill(16, Y_F1 + 2, 16, 18, Y_F1 + 2, 17, "minecraft:dark_oak_slab")
p.fill(16, Y_F1 + 1, 15, 18, Y_F1 + 1, 15, "minecraft:dark_oak_stairs", states(weirdo_direction=2))
p.fill(16, Y_F1 + 1, 18, 18, Y_F1 + 1, 18, "minecraft:dark_oak_stairs", states(weirdo_direction=3))
p.block(16, Y_F1 + 3, 16, "minecraft:sea_lantern")
p.block(18, Y_F1 + 3, 17, "minecraft:sea_lantern")
p.fill(15, Y_F1 + 1, 20, IX2, Y_F1 + 1, 20, "minecraft:light_gray_carpet")

p.note("- lounge (south west) with fireplace and corner sofa")
p.fill(IX1, Y_F1 + 1, 14, 9, Y_F1 + 4, 14, "minecraft:polished_blackstone")
p.fill(6, Y_F1 + 1, 14, 8, Y_F1 + 2, 14, "minecraft:air")
p.fill(6, Y_F1 + 1, 14, 8, Y_F1 + 1, 14, "minecraft:campfire")
p.fill(6, Y_F1 + 3, 14, 8, Y_F1 + 3, 14, "minecraft:chiseled_quartz_block")
p.fill(IX1, Y_F1 + 1, 16, 9, Y_F1 + 1, 19, "minecraft:light_gray_carpet")
p.fill(6, Y_F1 + 1, 17, 9, Y_F1 + 1, 17, "minecraft:dark_oak_stairs", states(weirdo_direction=3))
p.fill(IX1, Y_F1 + 1, 18, IX1, Y_F1 + 1, 19, "minecraft:dark_oak_stairs", states(weirdo_direction=0))
p.block(9, Y_F1 + 1, 16, "minecraft:jukebox")
p.block(8, Y_F1 + 1, 20, "minecraft:flower_pot")
p.block(IX1, Y_F1 + 1, 20, "minecraft:flower_pot")

p.note("- entrance hall")
p.fill(11, Y_F1 + 1, 14, 13, Y_F1 + 1, 20, "minecraft:red_carpet")
p.block(10, Y_F1 + 1, 20, "minecraft:flower_pot")
p.block(13, Y_F1 + 1, 20, "minecraft:red_carpet")
p.fill(11, Y_F1 + 4, 16, 12, Y_F1 + 4, 19, "minecraft:sea_lantern")

p.note("- guest bathroom (north west), floor tiled at floor level so the door opens")
p.fill(IX1, Y_F1, IZ1, 8, Y_F1, 9, "minecraft:smooth_quartz")
p.block(IX1, Y_F1 + 1, 6, "minecraft:cauldron")
p.block(IX1, Y_F1 + 1, 9, "minecraft:cauldron")
p.block(6, Y_F1 + 1, 6, "minecraft:quartz_slab")
p.stairs(8, Y_F1 + 1, 9, "minecraft:quartz_stairs", 3)
p.block(8, Y_F1 + 2, 6, "minecraft:glass_pane")

p.note("- utility room / pantry (keep the cell behind the door clear)")
p.fill(IX1, Y_F1 + 1, 12, 7, Y_F1 + 1, 12, "minecraft:barrel")
p.block(8, Y_F1 + 1, 12, "minecraft:furnace")

p.note("staircase up to the first floor (east side of the hall, runs north)")
for step in range(5):
    z = 12 - step
    y = Y_F1 + 1 + step
    p.stairs_run(13, 13, z, y, "minecraft:dark_oak_stairs", 3)
    if y - 1 >= Y_F1 + 1:
        p.fill(13, Y_F1 + 1, z, 13, y - 1, z, "minecraft:dark_oak_planks")
p.note("stairwell opening through the first floor slab (top step stays in place)")
p.fill(13, Y_F2, 9, 13, Y_F2, 12, "minecraft:air")

# =============================================================================
# 05 - upper floor: master suite, second bedroom, library, bathroom
# =============================================================================
p = part("parts/05_upper_floor", "Upper floor: master suite, guest room, library, spa bathroom")

p.note("partitions")
p.fill(9, Y_F2 + 1, IZ1, 9, Y_F2 + 4, 12, "minecraft:quartz_block")
p.fill(14, Y_F2 + 1, IZ1, 14, Y_F2 + 4, 12, "minecraft:quartz_block")
p.fill(14, Y_F2 + 1, 9, 14, Y_F2 + 2, 10, "minecraft:air")
p.note("the west wing is entered from the landing, next to the stair head")
p.door(9, Y_F2 + 1, 6, direction=0)
p.note("bedroom wing divider")
p.fill(14, Y_F2 + 1, 14, 14, Y_F2 + 4, IZ2, "minecraft:quartz_block")
p.fill(14, Y_F2 + 1, 16, 14, Y_F2 + 2, 17, "minecraft:air")

p.note("- master bedroom (whole south west side)")
p.fill(IX1, Y_F2 + 1, 14, 13, Y_F2 + 1, IZ2, "minecraft:light_gray_carpet")
p.fill(6, Y_F2 + 1, 16, 9, Y_F2 + 1, 19, "minecraft:dark_oak_planks")
p.bed(7, Y_F2 + 1, 17, direction=0)
p.bed(8, Y_F2 + 1, 17, direction=0)
p.block(IX1, Y_F2 + 1, 17, "minecraft:barrel")
p.block(IX1, Y_F2 + 2, 17, "minecraft:lantern")
p.block(10, Y_F2 + 1, 17, "minecraft:barrel")
p.block(10, Y_F2 + 2, 17, "minecraft:lantern")
p.note("dresser + wall mounted screen, clear of the corridor at x11-x12")
p.fill(IX1, Y_F2 + 1, 14, IX1, Y_F2 + 2, 14, "minecraft:chest")
p.fill(7, Y_F2 + 2, 14, 10, Y_F2 + 3, 14, "minecraft:black_concrete")
p.block(12, Y_F2 + 1, 20, "minecraft:flower_pot")

p.note("- spa bathroom (north west), sunken jacuzzi with a walkway at x8")
p.fill(IX1, Y_F2, IZ1, 8, Y_F2, 12, "minecraft:smooth_quartz")
p.outline(IX1, 7, 7, 9, Y_F2 + 1, "minecraft:quartz_block")
p.block(6, Y_F2 + 1, 8, "minecraft:water")
p.block(IX1, Y_F2 + 1, 6, "minecraft:cauldron")
p.block(6, Y_F2 + 1, 6, "minecraft:quartz_slab")
p.block(IX1, Y_F2 + 3, 8, "minecraft:sea_lantern")

p.note("- walk in wardrobe, entered along the x8 walkway")
p.fill(IX1, Y_F2 + 1, 12, 7, Y_F2 + 2, 12, "minecraft:chest")
p.block(IX1, Y_F2 + 1, 11, "minecraft:barrel")

p.note("- library / office (north east)")
p.fill(15, Y_F2 + 1, IZ1, IX2, Y_F2 + 3, IZ1, "minecraft:bookshelf")
p.fill(IX2, Y_F2 + 1, 7, IX2, Y_F2 + 3, 9, "minecraft:bookshelf")
p.block(15, Y_F2 + 1, 7, "minecraft:enchanting_table")
p.fill(16, Y_F2 + 1, 10, 18, Y_F2 + 1, 10, "minecraft:dark_oak_planks")
p.block(17, Y_F2 + 1, 11, "minecraft:dark_oak_stairs", states(weirdo_direction=3))
p.block(16, Y_F2 + 2, 10, "minecraft:lantern")
p.fill(15, Y_F2 + 1, 12, IX2, Y_F2 + 1, 12, "minecraft:light_gray_carpet")

p.note("- guest bedroom (south east)")
p.fill(15, Y_F2 + 1, 14, IX2, Y_F2 + 1, IZ2, "minecraft:light_gray_carpet")
p.fill(16, Y_F2 + 1, 16, 18, Y_F2 + 1, 18, "minecraft:dark_oak_planks")
p.bed(17, Y_F2 + 1, 17, direction=0)
p.block(16, Y_F2 + 1, 17, "minecraft:barrel")
p.block(16, Y_F2 + 2, 17, "minecraft:lantern")
p.block(IX2, Y_F2 + 1, 20, "minecraft:chest")
p.block(15, Y_F2 + 1, 20, "minecraft:flower_pot")

p.note("landing at the top of the lower flight, and the corridor south")
p.fill(10, Y_F2 + 1, 6, 13, Y_F2 + 1, 7, "minecraft:red_carpet")
p.fill(11, Y_F2 + 1, 8, 12, Y_F2 + 1, 13, "minecraft:red_carpet")

p.note("upper flight to the roof terrace (west side of the hall, runs south)")
for step in range(5):
    z = 8 + step
    y = Y_F2 + 1 + step
    p.stairs_run(10, 10, z, y, "minecraft:dark_oak_stairs", 2)
    if y - 1 >= Y_F2 + 1:
        p.fill(10, Y_F2 + 1, z, 10, y - 1, z, "minecraft:dark_oak_planks")
p.note("stairwell opening through the roof deck (top step stays in place)")
p.fill(10, Y_ROOF, 8, 10, Y_ROOF, 11, "minecraft:air")

# =============================================================================
# 06 - roof terrace
# =============================================================================
p = part("parts/06_roof", "Roof terrace: hot tub, pergola, sun loungers, railing")

p.note("glass railing all the way round the roof")
p.outline(HX1 - 1, HZ1 - 1, HX2 + 1, HZ2 + 2, Y_ROOF + 1, "minecraft:glass_pane")
for cx in (HX1 - 1, HX2 + 1):
    for cz in (HZ1 - 1, HZ2 + 2):
        p.fill(cx, Y_ROOF + 1, cz, cx, Y_ROOF + 2, cz, "minecraft:quartz_pillar")
        p.block(cx, Y_ROOF + 3, cz, "minecraft:sea_lantern")

p.note("stair housing so the roof access is covered and nobody falls down the shaft")
p.walls(9, 7, 12, 14, Y_ROOF + 1, Y_ROOF + 3, "minecraft:white_concrete")
p.fill(9, Y_ROOF + 4, 7, 12, Y_ROOF + 4, 14, "minecraft:smooth_quartz")
p.fill(10, Y_ROOF + 1, 14, 11, Y_ROOF + 2, 14, "minecraft:air")
p.fill(9, Y_ROOF + 2, 7, 12, Y_ROOF + 2, 7, "minecraft:glass")
p.block(10, Y_ROOF + 3, 10, "minecraft:sea_lantern")

p.note("hot tub")
p.fill(15, Y_ROOF + 1, 15, 18, Y_ROOF + 1, 18, "minecraft:smooth_quartz")
p.fill(16, Y_ROOF + 1, 16, 17, Y_ROOF + 1, 17, "minecraft:water")
p.block(15, Y_ROOF + 1, 15, "minecraft:sea_lantern")
p.block(18, Y_ROOF + 1, 18, "minecraft:sea_lantern")
p.stairs(19, Y_ROOF + 1, 16, "minecraft:quartz_stairs", 0)
p.stairs(19, Y_ROOF + 1, 17, "minecraft:quartz_stairs", 0)

p.note("pergola lounge")
for px, pz in ((6, 15), (6, 19), (9, 15), (9, 19)):
    p.fill(px, Y_ROOF + 1, pz, px, Y_ROOF + 3, pz, "minecraft:dark_oak_fence")
p.fill(6, Y_ROOF + 4, 15, 9, Y_ROOF + 4, 19, "minecraft:dark_oak_fence")
p.fill(6, Y_ROOF + 1, 16, 9, Y_ROOF + 1, 18, "minecraft:light_gray_carpet")
p.stairs(7, Y_ROOF + 1, 17, "minecraft:quartz_stairs", 3)
p.stairs(8, Y_ROOF + 1, 17, "minecraft:quartz_stairs", 3)
p.block(7, Y_ROOF + 1, 16, "minecraft:quartz_slab")

p.note("planters and deck lighting")
for px, pz in ((5, 7), (5, 11), (19, 7), (19, 11), (5, 20), (19, 20)):
    p.block(px, Y_ROOF + 1, pz, "minecraft:smooth_quartz")
    p.block(px, Y_ROOF + 2, pz, "minecraft:oak_leaves")
for lx, lz in ((6, 6), (18, 6), (6, 21), (18, 21), (12, 21)):
    p.block(lx, Y_ROOF, lz, "minecraft:sea_lantern")

# =============================================================================
# 07 - pool and pool deck
# =============================================================================
p = part("parts/07_pool", "East wing: swimming pool, deck, loungers")

PX1, PX2 = 23, 28
PZ1, PZ2 = 8, 18

p.note("pool deck")
p.fill(21, Y_GROUND, HZ1 - 1, 29, Y_GROUND, HZ2 + 2, "minecraft:smooth_quartz")
p.fill(21, Y_GROUND - 1, HZ1 - 1, 29, Y_GROUND - 1, HZ2 + 2, "minecraft:polished_blackstone")

p.note("pool basin")
p.fill(PX1, Y_GROUND - 4, PZ1, PX2, Y_GROUND, PZ2, "minecraft:quartz_block")
p.fill(PX1 + 1, Y_GROUND - 3, PZ1 + 1, PX2 - 1, Y_GROUND, PZ2 - 1, "minecraft:water")
p.note("underwater lighting")
for lz in (PZ1 + 2, PZ1 + 5, PZ1 + 8):
    p.block(PX1, Y_GROUND - 2, lz, "minecraft:sea_lantern")
    p.block(PX2, Y_GROUND - 2, lz, "minecraft:sea_lantern")
p.block(PX1 + 3, Y_GROUND - 4, PZ1 + 5, "minecraft:gold_block")

p.note("pool ladder + diving board")
p.fill(PX1 + 1, Y_GROUND - 3, PZ2 - 1, PX1 + 1, Y_GROUND, PZ2 - 1, "minecraft:ladder",
       states(facing_direction=2))
p.fill(25, Y_GROUND + 1, PZ1 - 2, 26, Y_GROUND + 1, PZ1 - 1, "minecraft:quartz_slab")

p.note("sun loungers and parasols along the west edge of the deck")
for lz in (10, 13, 16):
    p.stairs(21, Y_GROUND + 1, lz, "minecraft:quartz_stairs", 0)
    p.block(22, Y_GROUND + 1, lz, "minecraft:quartz_slab")
for uz in (11, 15):
    p.fill(21, Y_GROUND + 1, uz, 21, Y_GROUND + 2, uz, "minecraft:dark_oak_fence")
    p.fill(21, Y_GROUND + 3, uz - 1, 22, Y_GROUND + 3, uz + 1, "minecraft:white_concrete")

p.note("outdoor bar")
p.fill(22, Y_GROUND + 1, 19, 27, Y_GROUND + 1, 19, "minecraft:smooth_quartz")
p.fill(22, Y_GROUND + 2, 19, 27, Y_GROUND + 2, 19, "minecraft:quartz_slab")
p.block(23, Y_GROUND + 1, 20, "minecraft:barrel")
p.block(25, Y_GROUND + 1, 20, "minecraft:brewing_stand")
p.block(27, Y_GROUND + 1, 20, "minecraft:barrel")
p.fill(22, Y_GROUND + 3, 19, 27, Y_GROUND + 3, 19, "minecraft:sea_lantern")

p.note("deck lighting")
for lx, lz in ((22, 6), (29, 6), (29, 21), (22, 21)):
    p.lamp(lx, lz)

# =============================================================================
# 08 - grounds: driveway, fountain, garden, wall and gate
# =============================================================================
p = part("parts/08_grounds", "Grounds: driveway, fountain, gardens, perimeter wall")

p.note("driveway and front path")
p.fill(11, Y_GROUND, HZ2 + 3, 13, Y_GROUND, PLOT_Z[1], "minecraft:smooth_quartz")
p.fill(14, Y_GROUND, 26, 20, Y_GROUND, 29, "minecraft:polished_blackstone")

p.note("fountain")
p.fill(5, Y_GROUND, 25, 9, Y_GROUND, 29, "minecraft:smooth_quartz")
p.outline(5, 25, 9, 29, Y_GROUND + 1, "minecraft:quartz_block")
p.fill(6, Y_GROUND + 1, 26, 8, Y_GROUND + 1, 28, "minecraft:water")
p.fill(7, Y_GROUND + 1, 27, 7, Y_GROUND + 3, 27, "minecraft:quartz_pillar")
p.block(7, Y_GROUND + 4, 27, "minecraft:sea_lantern")
p.block(7, Y_GROUND + 2, 27, "minecraft:chiseled_quartz_block")

p.note("perimeter wall with gold posts, gate left open at the front")
p.outline(PLOT_X[0], PLOT_Z[0], PLOT_X[1], PLOT_Z[1], Y_GROUND + 1, "minecraft:quartz_block")
p.outline(PLOT_X[0], PLOT_Z[0], PLOT_X[1], PLOT_Z[1], Y_GROUND + 2, "minecraft:glass_pane")
p.fill(11, Y_GROUND + 1, PLOT_Z[1], 13, Y_GROUND + 2, PLOT_Z[1], "minecraft:air")
for cx in (PLOT_X[0], PLOT_X[1]):
    for cz in (PLOT_Z[0], PLOT_Z[1]):
        p.fill(cx, Y_GROUND + 1, cz, cx, Y_GROUND + 3, cz, "minecraft:quartz_pillar")
        p.block(cx, Y_GROUND + 4, cz, "minecraft:gold_block")
for gx in (10, 14):
    p.fill(gx, Y_GROUND + 1, PLOT_Z[1], gx, Y_GROUND + 3, PLOT_Z[1], "minecraft:quartz_pillar")
    p.block(gx, Y_GROUND + 4, PLOT_Z[1], "minecraft:sea_lantern")

p.note("hedges and trees")
p.fill(2, Y_GROUND + 1, 24, 9, Y_GROUND + 1, 24, "minecraft:oak_leaves")
p.fill(15, Y_GROUND + 1, 24, 20, Y_GROUND + 1, 24, "minecraft:oak_leaves")
p.fill(14, Y_GROUND + 1, 1, 28, Y_GROUND + 1, 1, "minecraft:oak_leaves")
for tx, tz in ((3, 27), (2, 17), (2, 10), (3, 2), (25, 2)):
    p.tree(tx, tz)

p.note("path lamps")
for lz in (25, 28):
    p.lamp(10, lz)
    p.lamp(14, lz)

p.note("back garden seating")
p.fill(6, Y_GROUND, 1, 12, Y_GROUND, 3, "minecraft:smooth_quartz")
p.stairs(8, Y_GROUND + 1, 2, "minecraft:quartz_stairs", 2)
p.stairs(9, Y_GROUND + 1, 2, "minecraft:quartz_stairs", 2)
p.stairs(10, Y_GROUND + 1, 2, "minecraft:quartz_stairs", 2)
p.block(11, Y_GROUND + 1, 2, "minecraft:campfire")

# =============================================================================
# 09 - lighting pass (no dark corners -> no mobs spawning indoors)
# =============================================================================
p = part("parts/09_lighting", "Lighting pass: recessed ceiling lights everywhere")

p.note("ground floor ceiling lights (kept clear of the stairwell shafts)")
for lx in (6, 16, 19):
    for lz in (7, 11, 15, 19):
        p.block(lx, Y_F2, lz, "minecraft:sea_lantern")
p.block(11, Y_F2, 7, "minecraft:sea_lantern")
p.block(11, Y_F2, 17, "minecraft:sea_lantern")
p.note("upper floor ceiling lights")
for lx in (6, 16, 19):
    for lz in (7, 11, 15, 19):
        p.block(lx, Y_ROOF, lz, "minecraft:sea_lantern")
p.block(13, Y_ROOF, 7, "minecraft:sea_lantern")
p.block(13, Y_ROOF, 17, "minecraft:sea_lantern")
p.note("porch and entrance lighting")
p.block(10, Y_F1 + 4, HZ2 + 1, "minecraft:sea_lantern")
p.block(14, Y_F1 + 4, HZ2 + 1, "minecraft:sea_lantern")
p.block(10, Y_F2 + 4, HZ2 + 1, "minecraft:sea_lantern")
p.block(14, Y_F2 + 4, HZ2 + 1, "minecraft:sea_lantern")


# =============================================================================
# top level functions
# =============================================================================
build = Part("build", "Build the whole luxury mansion around the player")
build.cmd('tellraw @s {"rawtext":[{"text":"§6[Luxury House] §fBuilding your mansion..."}]}')
build.cmd("")
for item in PARTS:
    build.cmd("function lux/%s" % item.name)
build.cmd("")
build.cmd("function lux/done")
PARTS.append(build)

done = Part("done", "Finishing touches and the welcome message")
done.cmd('titleraw @s title {"rawtext":[{"text":"§6Luxury House"}]}')
done.cmd('titleraw @s subtitle {"rawtext":[{"text":"§fYour mansion is ready"}]}')
done.cmd("playsound random.levelup @s ~ ~ ~ 1 1")
done.cmd('tellraw @s {"rawtext":[{"text":"§6[Luxury House] §aDone! §fThe front door is right in front of you."}]}')
done.cmd('tellraw @s {"rawtext":[{"text":"§7Pool on the east side, roof terrace up the stairs. Remove it again with §f/function lux/clear"}]}')
PARTS.append(done)

clear = Part("clear", "Remove the mansion and flatten the plot again")
clear.cmd('tellraw @s {"rawtext":[{"text":"§6[Luxury House] §fClearing the plot..."}]}')
clear.fill(PLOT_X[0], Y_GROUND + 1, PLOT_Z[0], PLOT_X[1], Y_ROOF + 8, PLOT_Z[1], "minecraft:air")
clear.fill(PLOT_X[0], Y_GROUND - 6, PLOT_Z[0], PLOT_X[1], Y_GROUND - 1, PLOT_Z[1], "minecraft:dirt")
clear.fill(PLOT_X[0], Y_GROUND, PLOT_Z[0], PLOT_X[1], Y_GROUND, PLOT_Z[1], "minecraft:grass_block")
clear.cmd('tellraw @s {"rawtext":[{"text":"§6[Luxury House] §aPlot cleared."}]}')
PARTS.append(clear)

help_fn = Part("help", "How to use the pack")
for line in [
    "§6=== Luxury House ===",
    "§f/function lux/build §7- build the mansion around you",
    "§f/function lux/clear §7- remove it again",
    "§f/function lux/help  §7- show this list",
    "§7Stand on flat ground, face north, leave about 31x31 blocks free.",
    "§7The house is built in front of you, the pool on your right.",
]:
    help_fn.cmd('tellraw @s {"rawtext":[{"text":"%s"}]}' % line)
PARTS.append(help_fn)


def main():
    if os.path.isdir(FUNC_DIR):
        shutil.rmtree(FUNC_DIR)
    os.makedirs(os.path.join(FUNC_DIR, "parts"))

    total = 0
    for item in PARTS:
        path, count = item.write(FUNC_DIR)
        total += count
        print("%-28s %4d commands" % (os.path.relpath(path, FUNC_DIR), count))
    print("-" * 42)
    print("%-28s %4d commands" % ("total", total))


if __name__ == "__main__":
    main()
