#!/usr/bin/env python3
"""Build the Parasite Apocalypse Survival add-on.

Steps (docs/TESTING.md):
  a) merge addon/fragments/lang/*.lang -> resource_pack/texts/en_US.lang
     (pack.* keys also -> behavior_pack/texts/en_US.lang) + texts/languages.json in both packs
  b) merge addon/fragments/item_texture/*.json -> resource_pack/textures/item_texture.json
  c) merge addon/fragments/sound_definitions/*.json -> resource_pack/sounds/sound_definitions.json
  d) deep-merge addon/fragments/sounds/*.json -> resource_pack/sounds.json
     (a key defined by two fragments is an error, for every merge)
  e) run tools/validate.py (build fails on validation errors)
  f) write dist/ParasiteApocalypseSurvival.mcaddon (top-level folders "Parasite Apocalypse BP/" and
     "Parasite Apocalypse RP/"), dist/ParasiteApocalypseSurvival_BP.mcpack, dist/ParasiteApocalypseSurvival_RP.mcpack
     and unpacked copies in dist/unpacked/ (git-ignored). Zips are deterministic: sorted entries,
     fixed timestamps (1980-01-01) and permissions.

Usage: python3 tools/build.py [--strict] [--skip-validate] [--no-package]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADDON = ROOT / "addon"
BP = ADDON / "behavior_pack"
RP = ADDON / "resource_pack"
FRAG = ADDON / "fragments"
DIST = ROOT / "dist"

ADDON_NAME = "ParasiteApocalypseSurvival"
BP_FOLDER = "Parasite Apocalypse BP"
RP_FOLDER = "Parasite Apocalypse RP"

GENERATED_HEADER = "## GENERATED by tools/build.py from addon/fragments/lang/*.lang - do not edit by hand"

ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)

# files/dirs never shipped inside a pack
JUNK_NAMES = {".DS_Store", "Thumbs.db", "desktop.ini", "__pycache__", ".git", ".gitkeep", ".gitignore", "node_modules"}
JUNK_SUFFIXES = (".pyc", ".py", ".md", ".psd", ".xcf", ".kra", ".blend", ".blend1", ".bak", ".tmp", ".swp", ".orig", "~", ".log")


class BuildError(Exception):
    pass


def rel(p: Path) -> str:
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p)


# ---------------------------------------------------------------------------
# strict JSON helpers
# ---------------------------------------------------------------------------

def _no_dupes(pairs):
    out = {}
    for k, v in pairs:
        if k in out:
            raise ValueError(f"duplicate key {k!r}")
        out[k] = v
    return out


def _bad_constant(name):
    raise ValueError(f"invalid JSON constant {name}")


def load_json_strict(path: Path):
    text = path.read_text(encoding="utf-8")
    if text.startswith("﻿"):
        raise BuildError(f"{rel(path)}: has a UTF-8 BOM")
    try:
        return json.loads(text, object_pairs_hook=_no_dupes, parse_constant=_bad_constant)
    except ValueError as e:
        raise BuildError(f"{rel(path)}: invalid JSON: {e}") from e


def dump_json(data) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def write_if_changed(path: Path, text: str, written: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    written.append(rel(path))


def fragment_files(sub: str, suffix: str) -> list[Path]:
    d = FRAG / sub
    if not d.is_dir():
        return []
    return sorted(p for p in d.iterdir() if p.is_file() and p.name.endswith(suffix))


# ---------------------------------------------------------------------------
# (a) lang
# ---------------------------------------------------------------------------

def parse_lang(path: Path) -> list[tuple[str, str, int]]:
    text = path.read_text(encoding="utf-8")
    if text.startswith("﻿"):
        text = text[1:]
    entries = []
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip("\r")
        s = line.strip()
        if not s or s.startswith("##"):
            continue
        if "=" not in line:
            raise BuildError(f"{rel(path)}:{n}: expected key=value, got {line!r}")
        key, value = line.split("=", 1)
        key = key.strip()
        # Bedrock treats "<TAB>##" as the start of a trailing comment
        if "\t##" in value:
            value = value.split("\t##", 1)[0]
        value = value.rstrip()
        if not key or any(c.isspace() for c in key):
            raise BuildError(f"{rel(path)}:{n}: invalid lang key {key!r}")
        entries.append((key, value, n))
    return entries


def build_lang(written: list[str]) -> dict:
    files = fragment_files("lang", ".lang")
    seen: dict[str, str] = {}
    blocks: list[tuple[str, list[tuple[str, str]]]] = []
    for f in files:
        items = []
        for key, value, n in parse_lang(f):
            where = f"{rel(f)}:{n}"
            if key in seen:
                raise BuildError(f"duplicate lang key {key!r}: {seen[key]} and {where}")
            seen[key] = where
            items.append((key, value))
        blocks.append((f.name, items))
    rp_lines = [GENERATED_HEADER]
    bp_lines = [GENERATED_HEADER + " (pack.* keys only)"]
    for name, items in blocks:
        rp_lines.append(f"## {name}")
        rp_lines.extend(f"{k}={v}" for k, v in items)
        for k, v in items:
            if k.startswith("pack."):
                bp_lines.append(f"{k}={v}")
    write_if_changed(RP / "texts" / "en_US.lang", "\n".join(rp_lines) + "\n", written)
    write_if_changed(BP / "texts" / "en_US.lang", "\n".join(bp_lines) + "\n", written)
    langs = dump_json(["en_US"])
    write_if_changed(RP / "texts" / "languages.json", langs, written)
    write_if_changed(BP / "texts" / "languages.json", langs, written)
    return {"fragments": len(files), "keys": len(seen)}


# ---------------------------------------------------------------------------
# (b) item_texture, (c) sound_definitions: flat merges
# ---------------------------------------------------------------------------

def flat_merge(sub: str, what: str) -> tuple[dict, int]:
    merged: dict = {}
    origin: dict[str, str] = {}
    files = fragment_files(sub, ".json")
    for f in files:
        data = load_json_strict(f)
        if not isinstance(data, dict):
            raise BuildError(f"{rel(f)}: {what} fragment must be a JSON object")
        for k, v in data.items():
            if k in merged:
                raise BuildError(f"duplicate {what} key {k!r}: {origin[k]} and {rel(f)}")
            merged[k] = v
            origin[k] = rel(f)
    return dict(sorted(merged.items())), len(files)


def build_item_texture(written: list[str]) -> dict:
    data, n = flat_merge("item_texture", "item_texture")
    for k, v in data.items():
        if not isinstance(v, dict) or "textures" not in v:
            raise BuildError(f"item_texture entry {k!r} must be an object with 'textures'")
    out = {"resource_pack_name": "pas", "texture_name": "atlas.items", "texture_data": data}
    write_if_changed(RP / "textures" / "item_texture.json", dump_json(out), written)
    return {"fragments": n, "textures": len(data)}


def build_sound_definitions(written: list[str]) -> dict:
    data, n = flat_merge("sound_definitions", "sound_definitions")
    for k, v in data.items():
        if not isinstance(v, dict) or not isinstance(v.get("sounds"), list):
            raise BuildError(f"sound definition {k!r} must be an object with a 'sounds' array")
    # same top-level layout as the vanilla resource_pack/sounds/sound_definitions.json
    out = {"format_version": "1.14.0", "sound_definitions": data}
    write_if_changed(RP / "sounds" / "sound_definitions.json", dump_json(out), written)
    return {"fragments": n, "sounds": len(data)}


# ---------------------------------------------------------------------------
# (d) sounds.json deep merge
# ---------------------------------------------------------------------------

def deep_merge(dst: dict, src: dict, path: str, origin: dict, src_name: str) -> None:
    for k, v in src.items():
        p = f"{path}/{k}"
        if k not in dst:
            dst[k] = v
            origin[p] = src_name
            continue
        if isinstance(dst[k], dict) and isinstance(v, dict):
            deep_merge(dst[k], v, p, origin, src_name)
            continue
        first = next((o for q, o in origin.items() if p == q or p.startswith(q + "/")), "another fragment")
        raise BuildError(f"sounds.json conflict at {p!r}: defined by {first} and {src_name}")


def sort_keys_deep(d):
    if isinstance(d, dict):
        return {k: sort_keys_deep(d[k]) for k in sorted(d)}
    if isinstance(d, list):
        return [sort_keys_deep(x) for x in d]
    return d


def build_sounds_json(written: list[str]) -> dict:
    merged: dict = {}
    origin: dict = {}
    files = fragment_files("sounds", ".json")
    for f in files:
        data = load_json_strict(f)
        if not isinstance(data, dict):
            raise BuildError(f"{rel(f)}: sounds fragment must be a JSON object")
        deep_merge(merged, data, "", origin, rel(f))
    write_if_changed(RP / "sounds.json", dump_json(sort_keys_deep(merged)), written)
    return {"fragments": len(files)}


# ---------------------------------------------------------------------------
# (e) validate
# ---------------------------------------------------------------------------

def run_validate(strict: bool) -> int:
    cmd = [sys.executable, str(ROOT / "tools" / "validate.py")]
    if strict:
        cmd.append("--strict")
    print(f"\n== validate: {' '.join(cmd[1:])}")
    proc = subprocess.run(cmd, cwd=ROOT)
    return proc.returncode


# ---------------------------------------------------------------------------
# (f) packaging
# ---------------------------------------------------------------------------

def is_junk(path: Path, base: Path) -> bool:
    for part in path.relative_to(base).parts:
        if part in JUNK_NAMES or part.startswith("."):
            return True
    return path.name.endswith(JUNK_SUFFIXES)


def pack_files(base: Path) -> list[Path]:
    return sorted(
        (p for p in base.rglob("*") if p.is_file() and not is_junk(p, base)),
        key=lambda p: p.relative_to(base).as_posix(),
    )


def _zip_dir(zf: zipfile.ZipFile, name: str) -> None:
    info = zipfile.ZipInfo(name if name.endswith("/") else name + "/", date_time=ZIP_EPOCH)
    info.create_system = 3
    info.external_attr = (0o40755 << 16) | 0x10
    info.compress_type = zipfile.ZIP_STORED
    zf.writestr(info, b"")


def _zip_file(zf: zipfile.ZipFile, name: str, data: bytes) -> None:
    info = zipfile.ZipInfo(name, date_time=ZIP_EPOCH)
    info.create_system = 3
    info.external_attr = 0o100644 << 16
    info.compress_type = zipfile.ZIP_DEFLATED
    zf.writestr(info, data, compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)


def write_zip(out: Path, trees: list[tuple[str, Path]]) -> dict:
    """trees: [(prefix inside zip ('' for root), source dir)]"""
    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_suffix(out.suffix + ".tmp")
    nfiles = 0
    raw = 0
    with zipfile.ZipFile(tmp, "w") as zf:
        for prefix, base in trees:
            files = pack_files(base)
            dirs = set()
            for f in files:
                parent = f.relative_to(base).parent
                while parent.as_posix() != ".":
                    dirs.add(parent.as_posix())
                    parent = parent.parent
            entries = [(d + "/", None) for d in dirs] + [(f.relative_to(base).as_posix(), f) for f in files]
            if prefix:
                entries.append(("", None))
            for name, src in sorted(entries, key=lambda e: e[0]):
                full = f"{prefix}/{name}" if prefix else name
                if src is None:
                    if full:
                        _zip_dir(zf, full)
                    continue
                data = src.read_bytes()
                raw += len(data)
                nfiles += 1
                _zip_file(zf, full, data)
    tmp.replace(out)
    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    return {"path": rel(out), "files": nfiles, "raw_bytes": raw, "zip_bytes": out.stat().st_size, "sha256": digest}


def write_unpacked() -> None:
    dst = DIST / "unpacked"
    if dst.exists():
        shutil.rmtree(dst)
    for folder, base in ((BP_FOLDER, BP), (RP_FOLDER, RP)):
        for f in pack_files(base):
            target = dst / folder / f.relative_to(base)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(f, target)


def check_pack_roots() -> None:
    for base in (BP, RP):
        if not (base / "manifest.json").is_file():
            raise BuildError(f"{rel(base)}/manifest.json is missing")


def human(n: int) -> str:
    for unit in ("B", "KiB", "MiB"):
        if n < 1024 or unit == "MiB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return str(n)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--strict", action="store_true", help="pass --strict to validate.py (missing content = error)")
    ap.add_argument("--skip-validate", action="store_true", help="do not run validate.py (not for releases)")
    ap.add_argument("--no-package", action="store_true", help="only merge fragments")
    args = ap.parse_args(argv)

    written: list[str] = []
    try:
        print("== merge fragments")
        s_lang = build_lang(written)
        print(f"  lang: {s_lang['fragments']} fragment(s), {s_lang['keys']} keys")
        s_tex = build_item_texture(written)
        print(f"  item_texture: {s_tex['fragments']} fragment(s), {s_tex['textures']} textures")
        s_sd = build_sound_definitions(written)
        print(f"  sound_definitions: {s_sd['fragments']} fragment(s), {s_sd['sounds']} sound ids")
        s_sj = build_sounds_json(written)
        print(f"  sounds.json: {s_sj['fragments']} fragment(s)")
        print("  wrote: " + (", ".join(written) if written else "(all generated files up to date)"))
    except BuildError as e:
        print(f"BUILD ERROR: {e}", file=sys.stderr)
        return 2

    if not args.skip_validate:
        rc = run_validate(args.strict)
        if rc != 0:
            print(f"BUILD FAILED: validate.py exited with {rc}", file=sys.stderr)
            return 1

    if args.no_package:
        return 0
    try:
        check_pack_roots()
    except BuildError as e:
        print(f"BUILD ERROR: {e}", file=sys.stderr)
        return 2
    print("\n== package")
    results = [
        write_zip(DIST / f"{ADDON_NAME}.mcaddon", [(BP_FOLDER, BP), (RP_FOLDER, RP)]),
        write_zip(DIST / f"{ADDON_NAME}_BP.mcpack", [("", BP)]),
        write_zip(DIST / f"{ADDON_NAME}_RP.mcpack", [("", RP)]),
    ]
    write_unpacked()
    for r in results:
        print(f"  {r['path']}: {r['files']} files, {human(r['raw_bytes'])} -> {human(r['zip_bytes'])}  sha256 {r['sha256'][:16]}")
    print(f"  unpacked copies: {rel(DIST / 'unpacked')}/ ({BP_FOLDER}, {RP_FOLDER})")
    print("BUILD OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
