execute if score #buildq npck.sys matches 0 if score #level npck.sys matches 1.. run function npck/build/house_1
execute if score #buildq npck.sys matches 1 if score #level npck.sys matches 1.. run function npck/build/house_2
execute if score #buildq npck.sys matches 2 if score #level npck.sys matches 1.. run function npck/build/storage
execute if score #buildq npck.sys matches 3 if score #level npck.sys matches 2.. run function npck/build/house_3
execute if score #buildq npck.sys matches 4 if score #level npck.sys matches 2.. run function npck/build/house_4
execute if score #buildq npck.sys matches 5 if score #level npck.sys matches 2.. run function npck/build/farm
execute if score #buildq npck.sys matches 6 if score #level npck.sys matches 3.. run function npck/build/town_hall
execute if score #buildq npck.sys matches 7 if score #level npck.sys matches 3.. run function npck/build/market
execute if score #buildq npck.sys matches 8 if score #level npck.sys matches 3.. run function npck/build/blacksmith
execute if score #buildq npck.sys matches 9 if score #level npck.sys matches 3.. run function npck/build/guard_tower
execute if score #buildq npck.sys matches 10 if score #level npck.sys matches 4.. run function npck/build/barracks
execute if score #buildq npck.sys matches 11 if score #level npck.sys matches 4.. run function npck/build/training_ground
execute if score #buildq npck.sys matches 12 if score #level npck.sys matches 4.. run function npck/build/hospital
execute if score #buildq npck.sys matches 13 if score #level npck.sys matches 4.. run function npck/build/stable
execute if score #buildq npck.sys matches 14 if score #level npck.sys matches 4.. run function npck/build/prison
execute if score #buildq npck.sys matches 15 if score #level npck.sys matches 4.. run function npck/build/walls
execute if score #buildq npck.sys matches 16 if score #level npck.sys matches 4.. run function npck/build/main_gate
execute if score #buildq npck.sys matches 17 if score #level npck.sys matches 5.. run function npck/build/castle
execute if score #buildq npck.sys matches 18 if score #level npck.sys matches 5.. run function npck/build/throne_room
execute if score #buildq npck.sys matches 19 if score #level npck.sys matches 5.. run function npck/build/treasury
