package com.loe.chat.ui.components

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.loe.chat.R
import com.loe.chat.ui.theme.LoeTheme

// The logo art lives in vector drawables generated by tools/logo/build_icons.py.

/** The gradient mascot on its own (used next to the "Loe" wordmark). */
@Composable
fun LoeMark(size: Dp, modifier: Modifier = Modifier) {
    Image(painterResource(R.drawable.loe_mark), contentDescription = null, modifier = modifier.size(size))
}

/** Mascot + "Loe" — the home screen header. */
@Composable
fun LoeWordmark(modifier: Modifier = Modifier, markSize: Dp = 32.dp, textSize: TextUnit = 28.sp) {
    Row(modifier, verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.Center) {
        LoeMark(markSize)
        Spacer(Modifier.width(6.dp))
        Text("Loe", fontSize = textSize, fontWeight = FontWeight.SemiBold, color = LoeTheme.colors.text)
    }
}

/** The launcher icon as a rounded square. */
@Composable
fun LoeAppIcon(size: Dp, modifier: Modifier = Modifier) {
    val glow = Color(0xFF4A35D6)
    Image(
        painterResource(R.drawable.loe_icon),
        contentDescription = null,
        modifier = modifier
            .size(size)
            .shadow(size * 0.08f, RoundedCornerShape(size * 0.24f), ambientColor = glow, spotColor = glow),
    )
}
