import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';

// Self-hosted fonts (SIL Open Font License) — latin subsets only, for speed.
import '@fontsource/orbitron/latin-500.css';
import '@fontsource/orbitron/latin-700.css';
import '@fontsource/rajdhani/latin-500.css';
import '@fontsource/rajdhani/latin-600.css';
import '@fontsource/rajdhani/latin-700.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/share-tech-mono/latin-400.css';

import './styles/global.css';
import { App } from './app/App';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// Dev-only scripting hook for tools/shoot.mjs (stripped from production builds).
if (import.meta.env.DEV) {
  void import('./app/devhook').then((m) => m.installDevHook());
}

// Offline support: register the service worker generated by vite-plugin-pwa.
if (import.meta.env.PROD && 'serviceWorker' in navigator) {
  import('virtual:pwa-register').then(({ registerSW }) => registerSW({ immediate: true })).catch(() => {});
}
