# clear.mcfunction - generated by tools/gen_mansion.py, do not edit
# Fills the entire build volume with air. Matches _index.json bounds.
fill ~-40 ~-30 ~-40 ~-20 ~2 ~ minecraft:air
fill ~-19 ~-30 ~-40 ~ ~2 ~ minecraft:air
fill ~-40 ~3 ~-40 ~-20 ~34 ~ minecraft:air
fill ~-19 ~3 ~-40 ~ ~34 ~ minecraft:air
fill ~-40 ~-30 ~1 ~-20 ~2 ~40 minecraft:air
fill ~-19 ~-30 ~1 ~ ~2 ~40 minecraft:air
fill ~-40 ~3 ~1 ~-20 ~34 ~40 minecraft:air
fill ~-19 ~3 ~1 ~ ~34 ~40 minecraft:air
fill ~1 ~-30 ~-40 ~40 ~2 ~-20 minecraft:air
fill ~1 ~-30 ~-19 ~40 ~2 ~ minecraft:air
fill ~1 ~3 ~-40 ~40 ~34 ~-20 minecraft:air
fill ~1 ~3 ~-19 ~40 ~34 ~ minecraft:air
fill ~1 ~-30 ~1 ~20 ~2 ~40 minecraft:air
fill ~21 ~-30 ~1 ~40 ~2 ~40 minecraft:air
fill ~1 ~3 ~1 ~20 ~34 ~40 minecraft:air
fill ~21 ~3 ~1 ~40 ~34 ~40 minecraft:air
