# part_48.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~1 ~-30 ~1 ~20 ~-14 ~20 minecraft:air
