# part_20.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~-19 ~-30 ~1 ~ ~-14 ~20 minecraft:air
