# part_56.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~1 ~3 ~1 ~20 ~18 ~20 minecraft:air
