# part_71.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 01 foundation + substructure excavation)
fill ~-15 ~-23 ~-21 ~15 ~-14 ~-3 minecraft:reinforced_deepslate
fill ~-14 ~-22 ~-20 ~14 ~-15 ~-4 minecraft:polished_deepslate
