# part_69.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~-40 ~-1 ~-40 ~40 ~-1 ~40 minecraft:grass_block
# Landscaped mounding and texture in the outer garden band.
setblock ~33 ~-1 ~9 minecraft:grass_block
setblock ~-2 ~-1 ~38 minecraft:moss_block
setblock ~33 ~-1 ~30 minecraft:podzol
setblock ~-35 ~-1 ~10 minecraft:moss_block
setblock ~-14 ~-1 ~22 minecraft:grass_block
setblock ~-38 ~-1 ~9 minecraft:moss_block
setblock ~28 ~-1 ~8 minecraft:grass_block
setblock ~20 ~-1 ~12 minecraft:grass_block
setblock ~-32 ~-1 ~29 minecraft:grass_block
setblock ~20 ~-1 ~32 minecraft:dirt["dirt_type":"coarse"]
setblock ~29 ~-1 ~5 minecraft:dirt["dirt_type":"coarse"]
setblock ~27 ~-1 ~8 minecraft:grass_block
setblock ~-32 ~-1 ~29 minecraft:grass_block
setblock ~-12 ~-1 ~17 minecraft:moss_block
setblock ~-16 ~-1 ~36 minecraft:grass_block
setblock ~-26 ~-1 ~32 minecraft:podzol
setblock ~21 ~-1 ~21 minecraft:moss_block
setblock ~-33 ~-1 ~34 minecraft:podzol
setblock ~37 ~-1 ~14 minecraft:dirt["dirt_type":"coarse"]
setblock ~-14 ~-1 ~23 minecraft:podzol
setblock ~30 ~-1 ~18 minecraft:grass_block
setblock ~29 ~-1 ~26 minecraft:podzol
setblock ~-14 ~-1 ~34 minecraft:podzol
setblock ~-25 ~-1 ~23 minecraft:grass_block
setblock ~-25 ~-1 ~15 minecraft:moss_block
setblock ~18 ~-1 ~18 minecraft:podzol
setblock ~2 ~-1 ~31 minecraft:moss_block
setblock ~-19 ~-1 ~22 minecraft:dirt["dirt_type":"coarse"]
setblock ~-6 ~-1 ~15 minecraft:moss_block
setblock ~-24 ~-1 ~5 minecraft:grass_block
setblock ~-17 ~-1 ~21 minecraft:moss_block
setblock ~33 ~-1 ~7 minecraft:podzol
setblock ~-30 ~-1 ~38 minecraft:moss_block
setblock ~-36 ~-1 ~7 minecraft:moss_block
setblock ~-28 ~-1 ~15 minecraft:podzol
setblock ~-8 ~-1 ~16 minecraft:podzol
setblock ~4 ~-1 ~20 minecraft:dirt["dirt_type":"coarse"]
setblock ~18 ~-1 ~16 minecraft:podzol
setblock ~-36 ~-1 ~26 minecraft:moss_block
setblock ~34 ~-1 ~19 minecraft:dirt["dirt_type":"coarse"]
setblock ~34 ~-1 ~33 minecraft:moss_block
setblock ~17 ~-1 ~27 minecraft:grass_block
setblock ~-28 ~-1 ~37 minecraft:moss_block
setblock ~-20 ~-1 ~26 minecraft:moss_block
setblock ~11 ~-1 ~26 minecraft:grass_block
setblock ~12 ~-1 ~10 minecraft:dirt["dirt_type":"coarse"]
setblock ~15 ~-1 ~30 minecraft:podzol
setblock ~-22 ~-1 ~33 minecraft:podzol
setblock ~-20 ~-1 ~27 minecraft:grass_block
setblock ~-18 ~-1 ~16 minecraft:podzol
setblock ~-27 ~-1 ~32 minecraft:podzol
setblock ~18 ~-1 ~23 minecraft:dirt["dirt_type":"coarse"]
# --- 01 foundation + substructure excavation ---
fill ~-20 ~-3 ~-28 ~20 ~-1 ~1 minecraft:polished_deepslate
# Basement void
