# part_84.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 28 detail pass - cladding, alarms, smart lighting)
setblock ~5 ~4 ~-1 myc:alarm_light
setblock ~ ~4 ~-26 myc:alarm_light
setblock ~-18 ~4 ~-13 myc:alarm_light
setblock ~18 ~4 ~-13 myc:alarm_light
setblock ~-5 ~11 ~-1 myc:alarm_light
setblock ~5 ~11 ~-1 myc:alarm_light
setblock ~-5 ~19 ~-1 myc:alarm_light
setblock ~5 ~19 ~-1 myc:alarm_light
setblock ~ ~25 ~-20 myc:alarm_light
setblock ~ ~-7 ~-22 myc:alarm_light
setblock ~ ~-19 ~-19 myc:alarm_light
# Smart lighting spine - redstone_lamp only where the emergency circuit should visibly take over
setblock ~-6 ~6 ~-25 minecraft:redstone_lamp
setblock ~6 ~6 ~-25 minecraft:redstone_lamp
setblock ~-6 ~6 ~-21 minecraft:redstone_lamp
setblock ~6 ~6 ~-21 minecraft:redstone_lamp
setblock ~-6 ~6 ~-17 minecraft:redstone_lamp
setblock ~6 ~6 ~-17 minecraft:redstone_lamp
setblock ~-6 ~6 ~-13 minecraft:redstone_lamp
setblock ~6 ~6 ~-13 minecraft:redstone_lamp
setblock ~-6 ~6 ~-9 minecraft:redstone_lamp
setblock ~6 ~6 ~-9 minecraft:redstone_lamp
setblock ~-6 ~6 ~-5 minecraft:redstone_lamp
setblock ~6 ~6 ~-5 minecraft:redstone_lamp
setblock ~-6 ~6 ~-1 minecraft:redstone_lamp
setblock ~6 ~6 ~-1 minecraft:redstone_lamp
setblock ~-7 ~14 ~-25 minecraft:redstone_lamp
setblock ~7 ~14 ~-25 minecraft:redstone_lamp
setblock ~-7 ~14 ~-20 minecraft:redstone_lamp
setblock ~7 ~14 ~-20 minecraft:redstone_lamp
setblock ~-7 ~14 ~-15 minecraft:redstone_lamp
setblock ~7 ~14 ~-15 minecraft:redstone_lamp
setblock ~-7 ~14 ~-10 minecraft:redstone_lamp
setblock ~7 ~14 ~-10 minecraft:redstone_lamp
setblock ~-7 ~14 ~-5 minecraft:redstone_lamp
setblock ~7 ~14 ~-5 minecraft:redstone_lamp
# Always-on architectural light so the house is never fully dark
setblock ~-18 ~5 ~-24 minecraft:sea_lantern
setblock ~18 ~5 ~-24 minecraft:sea_lantern
setblock ~-18 ~12 ~-24 minecraft:sea_lantern
setblock ~18 ~12 ~-24 minecraft:sea_lantern
setblock ~-18 ~5 ~-18 minecraft:sea_lantern
setblock ~18 ~5 ~-18 minecraft:sea_lantern
setblock ~-18 ~12 ~-18 minecraft:sea_lantern
setblock ~18 ~12 ~-18 minecraft:sea_lantern
setblock ~-18 ~5 ~-12 minecraft:sea_lantern
setblock ~18 ~5 ~-12 minecraft:sea_lantern
setblock ~-18 ~12 ~-12 minecraft:sea_lantern
setblock ~18 ~12 ~-12 minecraft:sea_lantern
setblock ~-18 ~5 ~-6 minecraft:sea_lantern
setblock ~18 ~5 ~-6 minecraft:sea_lantern
setblock ~-18 ~12 ~-6 minecraft:sea_lantern
setblock ~18 ~12 ~-6 minecraft:sea_lantern
# Facade uplighting
setblock ~-16 ~-1 ~1 minecraft:sea_lantern
setblock ~-12 ~-1 ~1 minecraft:sea_lantern
setblock ~-8 ~-1 ~1 minecraft:sea_lantern
setblock ~-4 ~-1 ~1 minecraft:sea_lantern
setblock ~ ~-1 ~1 minecraft:sea_lantern
setblock ~4 ~-1 ~1 minecraft:sea_lantern
setblock ~8 ~-1 ~1 minecraft:sea_lantern
setblock ~12 ~-1 ~1 minecraft:sea_lantern
setblock ~16 ~-1 ~1 minecraft:sea_lantern
# Screens and panels finishing the tech fit-out
setblock ~-6 ~2 ~-6 myc:screen
setblock ~6 ~2 ~-6 myc:screen
setblock ~-6 ~9 ~-8 myc:screen
setblock ~6 ~9 ~-8 myc:screen
setblock ~ ~-8 ~-22 myc:control_panel
setblock ~ ~-20 ~-19 myc:control_panel
