# part_38.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~21 ~-30 ~-19 ~40 ~-14 ~ minecraft:air
