# part_09.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 25 landscaped garden)
setblock ~-9 ~-1 ~6 minecraft:grass_path
setblock ~-10 ~-1 ~6 minecraft:grass_path
setblock ~-9 ~-1 ~8 minecraft:grass_path
setblock ~-10 ~-1 ~8 minecraft:grass_path
setblock ~-9 ~-1 ~10 minecraft:grass_path
setblock ~-10 ~-1 ~10 minecraft:grass_path
setblock ~-9 ~-1 ~12 minecraft:grass_path
setblock ~-10 ~-1 ~12 minecraft:grass_path
setblock ~-9 ~-1 ~14 minecraft:grass_path
setblock ~-10 ~-1 ~14 minecraft:grass_path
setblock ~-9 ~-1 ~16 minecraft:grass_path
setblock ~-10 ~-1 ~16 minecraft:grass_path
setblock ~-9 ~-1 ~18 minecraft:grass_path
setblock ~-10 ~-1 ~18 minecraft:grass_path
setblock ~-9 ~-1 ~20 minecraft:grass_path
setblock ~-10 ~-1 ~20 minecraft:grass_path
setblock ~-9 ~-1 ~22 minecraft:grass_path
setblock ~-10 ~-1 ~22 minecraft:grass_path
setblock ~-9 ~-1 ~24 minecraft:grass_path
setblock ~-10 ~-1 ~24 minecraft:grass_path
setblock ~-9 ~-1 ~26 minecraft:grass_path
setblock ~-10 ~-1 ~26 minecraft:grass_path
setblock ~-9 ~-1 ~28 minecraft:grass_path
setblock ~-10 ~-1 ~28 minecraft:grass_path
setblock ~-9 ~-1 ~30 minecraft:grass_path
setblock ~-10 ~-1 ~30 minecraft:grass_path
setblock ~-9 ~-1 ~32 minecraft:grass_path
setblock ~-10 ~-1 ~32 minecraft:grass_path
fill ~-16 ~-1 ~12 ~-12 ~-1 ~12 minecraft:grass_path
# Specimen trees
fill ~-16 ~ ~6 ~-16 ~5 ~6 minecraft:spruce_log
fill ~-18 ~4 ~4 ~-14 ~5 ~8 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
fill ~-17 ~6 ~5 ~-15 ~6 ~7 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
setblock ~-16 ~7 ~6 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
fill ~-13 ~ ~16 ~-13 ~4 ~16 minecraft:oak_log
fill ~-15 ~3 ~14 ~-11 ~4 ~18 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
fill ~-14 ~5 ~15 ~-12 ~5 ~17 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
setblock ~-13 ~6 ~16 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
fill ~-18 ~ ~24 ~-18 ~5 ~24 minecraft:spruce_log
fill ~-20 ~4 ~22 ~-16 ~5 ~26 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
fill ~-19 ~6 ~23 ~-17 ~6 ~25 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
setblock ~-18 ~7 ~24 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
fill ~-11 ~ ~30 ~-11 ~4 ~30 minecraft:oak_log
fill ~-13 ~3 ~28 ~-9 ~4 ~32 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
fill ~-12 ~5 ~29 ~-10 ~5 ~31 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
setblock ~-11 ~6 ~30 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
fill ~14 ~ ~31 ~14 ~5 ~31 minecraft:spruce_log
fill ~12 ~4 ~29 ~16 ~5 ~33 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
fill ~13 ~6 ~30 ~15 ~6 ~32 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
setblock ~14 ~7 ~31 minecraft:spruce_leaves["persistent_bit":true,"update_bit":false]
fill ~10 ~ ~29 ~10 ~4 ~29 minecraft:oak_log
fill ~8 ~3 ~27 ~12 ~4 ~31 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
fill ~9 ~5 ~28 ~11 ~5 ~30 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
setblock ~10 ~6 ~29 minecraft:oak_leaves["persistent_bit":true,"update_bit":false]
# Clipped hedging
fill ~-20 ~ ~3 ~-20 ~1 ~33 minecraft:azalea_leaves["persistent_bit":true,"update_bit":false]
fill ~-19 ~ ~34 ~-9 ~1 ~34 minecraft:azalea_leaves["persistent_bit":true,"update_bit":false]
fill ~-8 ~ ~12 ~-8 ~1 ~20 minecraft:azalea_leaves["persistent_bit":true,"update_bit":false]
# Flower beds - 1.21.0-safe species only
setblock ~-18 ~-1 ~8 minecraft:podzol
setblock ~-18 ~ ~8 minecraft:sunflower
setblock ~-17 ~-1 ~9 minecraft:podzol
setblock ~-17 ~ ~9 minecraft:sunflower
setblock ~-16 ~-1 ~10 minecraft:podzol
setblock ~-16 ~ ~10 minecraft:sunflower
setblock ~-15 ~-1 ~8 minecraft:podzol
setblock ~-15 ~ ~8 minecraft:peony
setblock ~-14 ~-1 ~10 minecraft:podzol
setblock ~-14 ~ ~10 minecraft:peony
setblock ~-18 ~-1 ~18 minecraft:podzol
setblock ~-18 ~ ~18 minecraft:sunflower
setblock ~-17 ~-1 ~19 minecraft:podzol
setblock ~-17 ~ ~19 minecraft:peony
setblock ~-16 ~-1 ~20 minecraft:podzol
setblock ~-16 ~ ~20 minecraft:rose_bush
setblock ~-15 ~-1 ~18 minecraft:podzol
setblock ~-15 ~ ~18 minecraft:lilac
setblock ~-14 ~-1 ~19 minecraft:podzol
setblock ~-14 ~ ~19 minecraft:sunflower
setblock ~-13 ~-1 ~26 minecraft:podzol
setblock ~-13 ~ ~26 minecraft:sunflower
setblock ~-14 ~-1 ~27 minecraft:podzol
setblock ~-14 ~ ~27 minecraft:rose_bush
setblock ~-15 ~-1 ~28 minecraft:podzol
setblock ~-15 ~ ~28 minecraft:peony
setblock ~-16 ~-1 ~26 minecraft:podzol
setblock ~-16 ~ ~26 minecraft:peony
setblock ~-17 ~-1 ~27 minecraft:podzol
setblock ~-17 ~ ~27 minecraft:rose_bush
# Ground cover and texture
setblock ~-18 ~ ~29 minecraft:pink_petals
setblock ~-9 ~ ~4 minecraft:flowering_azalea
setblock ~-12 ~ ~4 minecraft:azalea
setblock ~-15 ~ ~31 minecraft:short_grass
setblock ~-11 ~ ~16 minecraft:flowering_azalea
setblock ~-13 ~ ~24 minecraft:flowering_azalea
setblock ~-20 ~ ~32 minecraft:fern
setblock ~-18 ~ ~34 minecraft:flowering_azalea
setblock ~-9 ~ ~22 minecraft:pink_petals
setblock ~-16 ~ ~22 minecraft:flowering_azalea
setblock ~-16 ~ ~7 minecraft:flowering_azalea
setblock ~-16 ~ ~14 minecraft:azalea
setblock ~-12 ~ ~7 minecraft:azalea
setblock ~-13 ~ ~8 minecraft:short_grass
setblock ~-11 ~ ~3 minecraft:flowering_azalea
setblock ~-20 ~ ~12 minecraft:azalea
setblock ~-11 ~ ~30 minecraft:fern
setblock ~-9 ~ ~30 minecraft:fern
setblock ~-13 ~ ~29 minecraft:azalea
setblock ~-14 ~ ~26 minecraft:pink_petals
setblock ~-14 ~ ~15 minecraft:flowering_azalea
setblock ~-16 ~ ~15 minecraft:azalea
setblock ~-15 ~ ~24 minecraft:flowering_azalea
setblock ~-11 ~ ~21 minecraft:azalea
setblock ~-11 ~ ~24 minecraft:azalea
setblock ~-17 ~ ~20 minecraft:azalea
setblock ~-17 ~ ~27 minecraft:short_grass
setblock ~-12 ~ ~5 minecraft:short_grass
setblock ~-14 ~ ~24 minecraft:fern
setblock ~-11 ~ ~17 minecraft:flowering_azalea
setblock ~-13 ~ ~19 minecraft:short_grass
setblock ~-19 ~ ~6 minecraft:short_grass
setblock ~-19 ~ ~14 minecraft:fern
setblock ~-13 ~ ~20 minecraft:flowering_azalea
setblock ~-16 ~ ~18 minecraft:flowering_azalea
setblock ~-10 ~ ~16 minecraft:flowering_azalea
setblock ~-16 ~ ~11 minecraft:pink_petals
setblock ~-16 ~ ~4 minecraft:flowering_azalea
setblock ~-11 ~ ~17 minecraft:flowering_azalea
setblock ~-16 ~ ~30 minecraft:azalea
setblock ~-20 ~ ~4 minecraft:azalea
setblock ~-11 ~ ~10 minecraft:fern
setblock ~-14 ~ ~8 minecraft:short_grass
setblock ~-18 ~ ~24 minecraft:fern
setblock ~-15 ~ ~30 minecraft:flowering_azalea
setblock ~-9 ~ ~22 minecraft:flowering_azalea
setblock ~-18 ~ ~17 minecraft:azalea
setblock ~-9 ~ ~26 minecraft:short_grass
setblock ~-11 ~ ~17 minecraft:short_grass
setblock ~-15 ~ ~17 minecraft:fern
setblock ~-10 ~ ~16 minecraft:short_grass
setblock ~-16 ~ ~28 minecraft:short_grass
setblock ~-11 ~ ~18 minecraft:flowering_azalea
setblock ~-20 ~ ~23 minecraft:pink_petals
setblock ~-13 ~ ~4 minecraft:flowering_azalea
setblock ~-15 ~ ~6 minecraft:fern
setblock ~-17 ~ ~19 minecraft:short_grass
setblock ~-19 ~ ~30 minecraft:flowering_azalea
setblock ~-10 ~ ~10 minecraft:fern
setblock ~-14 ~ ~10 minecraft:flowering_azalea
setblock ~-11 ~ ~25 minecraft:flowering_azalea
setblock ~-11 ~ ~17 minecraft:azalea
setblock ~-10 ~ ~23 minecraft:short_grass
setblock ~-15 ~ ~34 minecraft:flowering_azalea
setblock ~-12 ~ ~29 minecraft:pink_petals
setblock ~-10 ~ ~18 minecraft:pink_petals
setblock ~-16 ~ ~19 minecraft:fern
setblock ~-9 ~ ~22 minecraft:azalea
setblock ~-16 ~ ~28 minecraft:pink_petals
setblock ~-20 ~ ~32 minecraft:short_grass
# Ornamental water feature
fill ~-14 ~-1 ~20 ~-11 ~-1 ~23 minecraft:calcite
fill ~-13 ~-1 ~21 ~-12 ~-1 ~22 minecraft:water
setblock ~-14 ~ ~20 minecraft:lantern["hanging":false]
setblock ~-14 ~ ~23 minecraft:lantern["hanging":false]
setblock ~-11 ~ ~20 minecraft:lantern["hanging":false]
setblock ~-11 ~ ~23 minecraft:lantern["hanging":false]
# Garden seating terrace
fill ~-19 ~-1 ~28 ~-13 ~-1 ~32 minecraft:smooth_stone
setblock ~-18 ~ ~31 minecraft:dark_oak_stairs["weirdo_direction":3,"upside_down_bit":false]
setblock ~-17 ~ ~31 minecraft:dark_oak_stairs["weirdo_direction":3,"upside_down_bit":false]
setblock ~-16 ~ ~31 minecraft:dark_oak_stairs["weirdo_direction":3,"upside_down_bit":false]
setblock ~-15 ~ ~31 minecraft:dark_oak_stairs["weirdo_direction":3,"upside_down_bit":false]
setblock ~-14 ~ ~31 minecraft:dark_oak_stairs["weirdo_direction":3,"upside_down_bit":false]
setblock ~-19 ~ ~31 minecraft:gray_wool
setblock ~-13 ~ ~31 minecraft:gray_wool
setblock ~-17 ~ ~29 minecraft:dark_oak_fence
setblock ~-17 ~ ~29 minecraft:dark_oak_fence
setblock ~-15 ~ ~29 minecraft:dark_oak_fence
setblock ~-15 ~ ~29 minecraft:dark_oak_fence
fill ~-17 ~1 ~29 ~-15 ~1 ~29 minecraft:quartz_slab
setblock ~-19 ~-1 ~27 minecraft:calcite
setblock ~-19 ~ ~27 minecraft:podzol
setblock ~-19 ~1 ~27 minecraft:flowering_azalea
setblock ~-16 ~-1 ~27 minecraft:calcite
setblock ~-16 ~ ~27 minecraft:podzol
