# part_00.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# --- 00 site clear + terrain pad ---
# Clear the working envelope, then lay ground.
fill ~-40 ~-30 ~-40 ~-20 ~-14 ~-20 minecraft:air
