# part_70.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 01 foundation + substructure excavation)
fill ~-17 ~-10 ~-25 ~17 ~-3 ~-2 minecraft:polished_deepslate
fill ~-16 ~-9 ~-24 ~16 ~-4 ~-3 minecraft:air
# Bunker void, deeper and armoured
