# part_11.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~-40 ~19 ~-19 ~-20 ~34 ~ minecraft:air
