# part_17.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~-40 ~-13 ~1 ~-20 ~2 ~20 minecraft:air
