# part_65.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~-40 ~-6 ~1 ~ ~-3 ~40 minecraft:stone
