# part_33.mcfunction - generated by tools/gen_mansion.py, do not edit
# Relative coordinates only; run via execute positioned <x> <y> <z>
# (continued: 00 site clear + terrain pad)
fill ~1 ~-13 ~-40 ~20 ~2 ~-20 minecraft:air
